In [1]:
import pandas as pd 
import numpy as np

CSV CANAIS DE VENDA

(p)coluna canal de venda tem 'ota' o que seria?
(t)coluna comissão pct esta em str


CSV CLIENTE

(t) clientes duplicados (3?)
(p) temos clientes com todas as informações idênticas salvo coluna de estado de origem 

(t) coluna de tipo de cliente precisa ser padroni.
(p) NaN existente, não deveria constar como nulo?
(t) coluna estado de origem tem que ser padroni.
(p) coluna faixa_etaria com muito NaN PERGUNTA DE NEGOCIO, É IMPORTANTE PARA A LEITURA DO NEGOCIO


CSV FUNCIONARIO

(t) Coluna salatio str
(p) coluna salario 6 NaN IMPORTANTE PARA A LEITURA?
(t) leta maiuscula na coluna cargo


CSV RESERVAS

(t) Coluna status reserva precisa ser padronizado
(t) NaN na coluna id_canal e avaliação_ cliente IMPORTANTE PARA LEITURA
(t) Coluna forma de pagamento precisa padronizar

CSV tipos quarto

(t) coluna valor diaria base como str


CSV UNIDADES

(t) regiao precisa padronizar espaço no serra
(t) categoria hotel padronizar, nome ext. str
(t) padronizar nome das regiões, csv conta com: Capital, Serra, capital, CAP,Baixada Fluminense, Baixada fluminense,Serra           
(t) numero de quartos esta float precisa ir para int
(p) número de quarto em Paraty e Petrópolis

In [2]:
pd.read_csv ('canais_venda.csv', sep=';')
pd.read_csv ('clientes.csv', sep=';')
pd.read_csv ('funcionarios.csv', sep=';')
pd.read_csv ('reservas.csv', sep=';')
pd.read_csv ('tipos_quarto.csv', sep=';')
pd.read_csv ('unidades.csv', sep=';')

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,70
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [3]:
df = pd.read_csv('unidades.csv', sep=';')

print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

(13, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

id_unidade                   int64
nome_unidade                   str
cidade                         str
regiao                         str
categoria_hotel(estrelas)    int64
num_quartos_total            int64
dtype: object

In [4]:
df[df.duplicated(subset=['num_quartos_total'], keep=False)]

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [5]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [id_unidade, nome_unidade, cidade, regiao, categoria_hotel(estrelas), num_quartos_total]
Index: []

In [6]:
df['categoria_hotel'].value_counts()

KeyError: 'categoria_hotel'

In [ ]:
mapa = {
    '4 estrelas':                '4',
    '4 Estrelas':                '4',
    '3*':                        '3',
    'Três Estrelas':             '3',
    '3 estrelas':               '3',
    '5 estrelas':                '5',
    'cinco estrelas':            '5'
}
df['categoria_hotel'] = df['categoria_hotel'].map(mapa).fillna(df['categoria_hotel'])

print('Após mapeamento:')
print(sorted(df['categoria_hotel'].unique()))

Após mapeamento:
['3', '4', '5']

In [ ]:
df['categoria_hotel'].value_counts()

categoria_hotel
4    5
5    4
3    3
Name: count, dtype: int64

In [ ]:
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,capital,4,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,CAP,4,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada fluminense,3,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50.0

In [ ]:
df['regiao'].value_counts()

regiao
Costa Verde           3
Capital               2
Serra                 2
capital               1
CAP                   1
Baixada Fluminense    1
Baixada fluminense    1
Serra                 1
Name: count, dtype: int64

In [ ]:
reg = {
    'capital':                'Capital',
    'CAP':                  'Capital',
    'Serra':                   'Serra',
     'Baixada fluminense':             'Baixada Fluminense'
}
df['regiao'] = df['regiao'].map(reg).fillna(df['regiao'])

print('Após mapeamento:')
print(sorted(df['regiao'].unique()))

Após mapeamento:
['Baixada Fluminense', 'Capital', 'Costa Verde', 'Serra', 'Serra ']

In [ ]:
df['regiao'] = df['regiao'].str.strip().str.title()
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50.0

In [ ]:
df['num_quartos_total'] = df['num_quartos_total'].astype("Int64")
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [ ]:
df = df.rename(columns={'categoria_hotel': 'categoria_hotel(estrelas)'})
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [ ]:
df['categoria_hotel(estrelas)'] = pd.to_numeric(df['categoria_hotel(estrelas)'], errors="coerce").astype("Int64")
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [ ]:
df.to_csv('unidades.csv', sep=';', index=False)
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50



CSV UNIDADES

(t) padronizado categoria hotel, deixados apenas números, 
(t) padronizado nome das regiões: Capital, Serra, Baixada Fluminense, Costa Verde           
(t) numero de quartos esta float precisa ir para int
(p) número de quarto em Paraty e Petrópolis

In [134]:
df_tipo = pd.read_csv('tipos_quarto.csv', sep=';')

print(df_tipo.shape)
display(df_tipo.head())
display(df_tipo.tail())
display(df_tipo.dtypes)

(8, 4)

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
0               1      Standard               2              280.0
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0

   id_tipo_quarto                descricao  capacidade_max  valor_diaria_base
3               4                    Suite               4              950.0
4               5             Suíte Master               4             1500.0
5               6          Suíte Vista Mar               2              620.0
6               7  Suíte Master Copacabana               3              780.0
7               8   Cobertura Presidencial               4              950.0

id_tipo_quarto         int64
descricao                str
capacidade_max         int64
valor_diaria_base    float64
dtype: object

In [135]:
df_tipo['descricao'] = df_tipo['descricao'].str.strip().str.title()
df_tipo

   id_tipo_quarto                descricao  capacidade_max  valor_diaria_base
0               1                 Standard               2              280.0
1               2                 Superior               2              420.0
2               3                   Deluxe               3              580.0
3               4                    Suite               4              950.0
4               5             Suíte Master               4             1500.0
5               6          Suíte Vista Mar               2              620.0
6               7  Suíte Master Copacabana               3              780.0
7               8   Cobertura Presidencial               4              950.0

In [ ]:
df_tipo['valor_diaria_base'] = (
df_tipo['valor_diaria_base']
.str.replace('R$', '', regex=False)
.str.replace(' ', '', regex=False)
.str.replace('.', '', regex=False) # remove separador de milhar
.str.replace(',', '.', regex=False)
.astype(float)
)

AttributeError: Can only use .str accessor with string values, not floating

In [ ]:
df_tipo.to_csv('tipos_quarto.csv', sep=';', index=False)

In [ ]:
df_tipo

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
0               1      Standard               2              280.0
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0
5               3        Deluxe               3              580.0

padronizado a escrita da couna 'descrição'
coluna 'valor_diaria_base'

In [ ]:
df_res = pd.read_csv('reservas.csv', sep=';')
df_re

print(df_res.shape)
display(df_res.head())
display(df_res.tail())
display(df_res.dtypes)

In [ ]:
df_res['data_checkin'] = pd.to_datetime(
    df_res['data_checkin'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [ ]:
df_res['data_checkout'] = pd.to_datetime(
    df_res['data_checkout'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [ ]:


print (df_res['status_reserva'].sort_values().unique())


print(df_res['forma_pagamento'].sort_values().unique())

<StringArray>
[   'Cancel.',  'Cancelada',  'Concluida',  'Concluída',      'Conf.',
 'Confirmada',    'No-Show']
Length: 7, dtype: str
<StringArray>
[       'C. Crédito',    'Cartao Credito',     'Cartao Debito',
 'Cartão De Crédito',  'Cartão De Débito',              'Cash',
                'Cc',                'Cd',              'Cred',
          'Dinheiro',               'Déb',               'Pix',
               'Ted',     'Transferencia',     'Transferência']
Length: 15, dtype: str

In [ ]:
rese = {
    'Cancel.':                'Capital',
    'CAP':                  'Capital',
    'Serra':                   'Serra',
     'Baixada fluminense':             'Baixada Fluminense'
}
df['reseiao'] = df['reseiao'].map(rese).fillna(df['regiao'])

print('Após mapeamento:')
print(sorted(df['regiao'].unique()))

In [ ]:

df_res['status_reserva'] = df_res['status_reserva'].str.strip().str.title()
df_res['forma_pagamento'] = df_res['forma_pagamento'].str.strip().str.title()
df_res

In [ ]:
df_res.to_csv('reservas.csv', sep=';', index=False)
df_res

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,Confirmada,Cartão De Crédito
1,2,5,1,261,4.0,2023-09-28,2023-01-10,3,2,1.0,Concluída,Pix
2,3,10,4,49,4.0,2023-01-08,2023-06-08,5,1,9.0,Concluída,Cartão De Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,Cancelada,Pix
4,5,7,1,42,1.0,2023-12-01,2023-01-19,7,1,6.0,Confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
2452,2453,10,3,210,4.0,2023-10-22,2023-10-27,5,1,9.0,Confirmada,Cartão De Débito
2453,2454,7,3,271,2.0,2024-08-08,2024-08-14,6,2,6.0,Confirmada,Pix
2454,2455,7,1,143,1.0,2023-07-26,2023-07-27,1,2,6.0,Confirmada,Transferência
2455,2456,8,4,176,1.0,2023-10-05,2023-05-17,7,1,6.0,Concluída,Cartão De Débito
2456,2457,6,3,160,1.0,2023-01-07,2023-05-07,4,1,9.0,Confirmada,Cartão De Crédito

alterado para datetime data checkin e checkout
nome com letra maisúcula status reserva e forma de pagamento

In [89]:
df_fun = pd.read_csv('funcionarios.csv', sep=';')
df_fun

print(df_fun.shape)
display(df_fun.head())
display(df_fun.tail())
display(df_fun.dtypes)

(134, 7)

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar De Limpeza,Governança,2139.0,2020-05-10
1,2,1,Abel Correia,Segurança,Segurança,1746.0,2021-12-29
2,3,1,Sara Teixeira,Analista Financeiro,Financeiro,5356.0,2022-01-03
3,4,1,Julia Monteiro,Auxiliar De Limpeza,Governança,2070.0,2019-10-06
4,5,1,Daniela Ramos,Auxiliar De Limpeza,Governança,1572.0,2018-10-16

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
129,130,12,Fernanda Cruz,Manutenção,Manutenção,2221.0,2020-08-16
130,131,12,Abel Correia,Gerente,Administração,8404.0,2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,2700.0,2021-01-22
132,133,12,Yuri Castro,Segurança,Segurança,1976.0,2021-08-10
133,134,12,Eduardo Lopes,Recepcionista,Recepção,2442.0,2023-02-17

id_funcionario      int64
id_unidade          int64
nome                  str
cargo                 str
departamento          str
salario           float64
data_admissao         str
dtype: object

In [ ]:
df_fun['cargo'] = df_fun['cargo'].str.strip().str.title()

In [ ]:

df_fun['cargo'].value_counts()

cargo
Manutenção             24
Camareira              21
Segurança              20
Auxiliar De Limpeza    17
Recepcionista          15
Cozinheiro             15
Analista Financeiro    13
Gerente                 9
Name: count, dtype: int64

In [90]:

df_fun['departamento'].value_counts()

departamento
Governança             38
Manutenção             24
Segurança              20
Recepção               15
Alimentos e Bebidas    15
Financeiro             13
Administração           9
Name: count, dtype: int64

In [ ]:

dep = {
    'Gov.':                'Governança',
    'Admin.':                  'Administração',
    'A&B':                   'Alimentos e Bebidas',
     'Baixada fluminense':             'Baixada Fluminense'
}
df_fun['departamento'] = df_fun['departamento'].map(dep).fillna(df_fun['departamento'])

print('Após mapeamento:')
print(sorted(df_fun['departamento'].unique()))

Após mapeamento:
['Administração', 'Alimentos e Bebidas', 'Financeiro', 'Governança', 'Manutenção', 'Recepção', 'Segurança']

In [ ]:

df_fun['salario'] = (
df_fun['salario']
.str.replace('.', '', regex=False)
.str.replace('"', '', regex=False)
.str.replace(',', '.', regex=False)
.astype(float)
)

AttributeError: Can only use .str accessor with string values, not floating

In [91]:

df_fun['data_admissao'] = pd.to_datetime(
    df_fun['data_admissao'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [92]:
df_fun.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  134 non-null    int64
 1   id_unidade      134 non-null    int64
 2   nome            134 non-null    str
 3   cargo           134 non-null    str
 4   departamento    134 non-null    str
 5   salario         128 non-null    float64
 6   data_admissao   134 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 7.5 KB

In [93]:
display(df_fun.dtypes)
df_fun.to_csv('funcionarios.csv', sep=';', index=False)
df_fun

id_funcionario             int64
id_unidade                 int64
nome                         str
cargo                        str
departamento                 str
salario                  float64
data_admissao     datetime64[us]
dtype: object

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar De Limpeza,Governança,2139.0,2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,1746.0,2021-12-29
2,3,1,Sara Teixeira,Analista Financeiro,Financeiro,5356.0,2022-03-01
3,4,1,Julia Monteiro,Auxiliar De Limpeza,Governança,2070.0,2019-06-10
4,5,1,Daniela Ramos,Auxiliar De Limpeza,Governança,1572.0,2018-10-16
...,...,...,...,...,...,...,...
129,130,12,Fernanda Cruz,Manutenção,Manutenção,2221.0,2020-08-16
130,131,12,Abel Correia,Gerente,Administração,8404.0,2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,2700.0,2021-01-22
132,133,12,Yuri Castro,Segurança,Segurança,1976.0,2021-10-08
133,134,12,Eduardo Lopes,Recepcionista,Recepção,2442.0,2023-02-17

padronizado escrita cargo, com letras maisuculas
padronizado departamento tirado abreviações
sálario padronizado para float e retirado datas
data admissao para datetime

In [159]:
df_cli = pd.read_csv ('clientes.csv', sep=';')
df_cli
print(df_cli.shape)
display(df_cli.head())
display(df_cli.tail())
display(df_cli.dtypes)

(301, 6)

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,Corporativo
1,2,Larissa Sousa,Curitiba,PR,18-25,Pessoa Física
2,3,Tatiana Coelho,Rio de Janeiro,RJ,65+,Corporativo
3,4,Wilson Duarte,Brasília,DF,26-35,Corporativo
4,5,Gabriela Lima,Rio de Janeiro,RJ,46-55,Pessoa Física

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
296,297,Roberta Leite,Curitiba,PR,56-65,Pessoa Física
297,298,Eduardo Lopes,São Paulo,SP,36-45,Corporativo
298,299,Vanessa Cavalcanti,Curitiba,PR,46-55,Pessoa Física
299,300,Julia Monteiro,Brasília,DF,36-45,Corporativo
300,47,Carlos Neto,Niterói,RJ,36-45,Corporativo

id_cliente       int64
nome               str
cidade_origem      str
estado_origem      str
faixa_etaria       str
tipo_cliente       str
dtype: object

In [ ]:
df_cli[df_cli.isnull().any(axis=1)]

In [ ]:

df_cli['cidade_origem'].sort_values().unique()

<StringArray>
['Belo Horizonte',       'Brasília',       'Curitiba',      'Fortaleza',
        'Niterói',         'Recife', 'Rio de Janeiro',       'Salvador',
      'São Paulo']
Length: 9, dtype: str

In [ ]:
df_cli['estado_origem'].sort_values()

In [ ]:
print(sorted(df_cli['cidade_origem'].unique()))
print(sorted(df_cli['estado_origem'].unique()))

['Belo Horizonte', 'Brasília', 'Curitiba', 'Fortaleza', 'Niterói', 'Recife', 'Rio de Janeiro', 'Salvador', 'São Paulo']
['BA', 'CE', 'DF', 'MG', 'PE', 'PR', 'RJ', 'SP']

In [ ]:
mapa_cidades = {
    'r.j.': 'RJ',
    'rj': 'RJ',
    'Rio de Janeiro': 'RJ'
}

df_cli['estado_origem'] = df_cli['estado_origem'].map(mapa_cidades).fillna(df_cli['estado_origem'])

print('Após mapeamento:')
print(sorted(df_cli['estado_origem'].unique()))

Após mapeamento:
['AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MG', 'PA', 'PE', 'PR', 'RJ', 'RS', 'SC', 'SP']

In [ ]:
mapa_cidade_estado = {
    "Belo Horizonte": "MG",
    "Brasília": "DF",
    "Curitiba": "PR",
    "Fortaleza": "CE",
    "Niterói": "RJ",
    "Recife": "PE",
    "Rio de Janeiro": "RJ",
    "Salvador": "BA",
    "São Paulo": "SP"
}


df_cli['estado_origem'] = df_cli['cidade_origem'].map(mapa_cidade_estado).fillna(df_cli['estado_origem'])


df_cli

In [ ]:
df_cli['tipo_cliente'].sort_values().unique()
print(sorted(df_cli['tipo_cliente'].unique()))

['Corporativo', 'Pessoa Física']

In [ ]:
tipo = {
    'PF':   'Pessoa Física',
    'pessoa fisica':    'Pessoa Física',
    'pf':   'Pessoa Física',
    'PJ':   'Corporativo',
    'corporativo':  'Corporativo'
}

df_cli['tipo_cliente'] = df_cli['tipo_cliente'].map(tipo).fillna(df_cli['tipo_cliente'])

print('Após mapeamento:')
print(sorted(df_cli['tipo_cliente'].unique()))

Após mapeamento:
['Corporativo', 'Pessoa Física']

In [179]:
df_cli.loc[df_cli['id_cliente'] == 401, 'id_cliente'] = 401
df_cli.loc[(df_cli['id_cliente'] == 401)]

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
300,401,Carlos Neto,Niterói,RJ,36-45,Corporativo

In [174]:
df_cli.loc[300, 'id_cliente'] = 401
df_cli.iloc[46, :]

id_cliente                  47
nome             Wesley Araujo
cidade_origem           Recife
estado_origem               PE
faixa_etaria               65+
tipo_cliente     Pessoa Física
Name: 46, dtype: object

In [180]:
df_cli
df_cli.to_csv('clientes.csv', sep=';', index=False)

espelhado dados de estado de acordo com a cidade
padronizado escrita do tipo cliente
alterado id de cliente do Carlos Neto de 47 o que conflitava com o mesmo id de Wesley, para 401

In [ ]:
df_can = pd.read_csv('canais_venda.csv', sep=';')

print(df_tipo.shape)
display(df_tipo.head())
display(df_tipo.tail())
display(df_tipo.dtypes)

(6, 4)

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
0               1      Standard               2              280.0
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0
5               3        Deluxe               3              580.0

id_tipo_quarto         int64
descricao                str
capacidade_max         int64
valor_diaria_base    float64
dtype: object

trabalhar no novos csvs

In [127]:
df_uni = pd.read_csv('unidades_novos.csv', sep=';')

print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

df.info()

(13, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

id_unidade                   int64
nome_unidade                   str
cidade                         str
regiao                         str
categoria_hotel(estrelas)    int64
num_quartos_total            int64
dtype: object

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_unidade                 13 non-null     int64
 1   nome_unidade               13 non-null     str
 2   cidade                     13 non-null     str
 3   regiao                     13 non-null     str
 4   categoria_hotel(estrelas)  13 non-null     int64
 5   num_quartos_total          13 non-null     int64
dtypes: int64(3), str(3)
memory usage: 756.0 bytes

In [128]:

df = pd.concat([df, df_uni], ignore_index=True)
print (df.shape) 
display (df.head(13))
print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

(14, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,70
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

(14, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40
13,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

id_unidade                   int64
nome_unidade                   str
cidade                         str
regiao                         str
categoria_hotel(estrelas)    int64
num_quartos_total            int64
dtype: object

In [129]:
df ['num_quartos_total'] = df ['num_quartos_total'].astype('Int64')
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,70
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40
13,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [130]:
df.info()
df.duplicated().sum()
df[df.duplicated(keep=False)]

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_unidade                 14 non-null     int64
 1   nome_unidade               14 non-null     str
 2   cidade                     14 non-null     str
 3   regiao                     14 non-null     str
 4   categoria_hotel(estrelas)  14 non-null     int64
 5   num_quartos_total          14 non-null     Int64
dtypes: Int64(1), int64(2), str(3)
memory usage: 818.0 bytes

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40
13,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [132]:
df = df.drop_duplicates()
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,70
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [ ]:

df.loc[6, "num_quartos_total"] = 70
df.loc[9, "num_quartos_total"] = 75

In [133]:
df.to_csv('unidades.concat.csv', sep=';', index=False)
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,70
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

concatenado csv unidades
preenchido os números de quartos

In [125]:
df_tipon = pd.read_csv('tipos_quarto_novos.csv', sep=';')
print (df_tipon.shape)
print (df_tipon.dtypes)
df_tipon

(3, 4)
id_tipo_quarto         int64
descricao                str
capacidade_max         int64
valor_diaria_base    float64
dtype: object

   id_tipo_quarto                descricao  capacidade_max  valor_diaria_base
0               6          Suíte Vista Mar               2              620.0
1               7  Suíte Master Copacabana               3              780.0
2               8   Cobertura Presidencial               4              950.0

In [136]:
df_tipo_qt = pd.concat([df_tipo, df_tipon], ignore_index=True)

In [137]:
df_tipo_qt

    id_tipo_quarto                descricao  capacidade_max  valor_diaria_base
0                1                 Standard               2              280.0
1                2                 Superior               2              420.0
2                3                   Deluxe               3              580.0
3                4                    Suite               4              950.0
4                5             Suíte Master               4             1500.0
5                6          Suíte Vista Mar               2              620.0
6                7  Suíte Master Copacabana               3              780.0
7                8   Cobertura Presidencial               4              950.0
8                6          Suíte Vista Mar               2              620.0
9                7  Suíte Master Copacabana               3              780.0
10               8   Cobertura Presidencial               4              950.0

In [138]:
df_tipo_qt = df_tipo_qt.drop_duplicates()
df_tipo_qt

   id_tipo_quarto                descricao  capacidade_max  valor_diaria_base
0               1                 Standard               2              280.0
1               2                 Superior               2              420.0
2               3                   Deluxe               3              580.0
3               4                    Suite               4              950.0
4               5             Suíte Master               4             1500.0
5               6          Suíte Vista Mar               2              620.0
6               7  Suíte Master Copacabana               3              780.0
7               8   Cobertura Presidencial               4              950.0

In [139]:
df_tipo_qt.to_csv('tipos_quarto.concat.csv', sep=';', index=False)

concatenado tipo quarto

In [8]:
df_res = pd.read_csv ('reservas.csv', sep=';')
df_reser = pd.read_csv('reservas_novas.csv', sep=';')
df_reser.info()
df_res.info()

<class 'pandas.DataFrame'>
RangeIndex: 2207 entries, 0 to 2206
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_reserva         2207 non-null   int64
 1   id_unidade         2207 non-null   int64
 2   id_tipo_quarto     2207 non-null   int64
 3   id_cliente         2207 non-null   int64
 4   id_canal           2110 non-null   float64
 5   data_checkin       2207 non-null   str
 6   data_checkout      2207 non-null   str
 7   qtd_diarias        2207 non-null   int64
 8   num_hospedes       2207 non-null   int64
 9   avaliacao_hospede  1898 non-null   float64
 10  status_reserva     2207 non-null   str
 11  forma_pagamento    2207 non-null   str
dtypes: float64(2), int64(6), str(4)
memory usage: 207.0 KB
<class 'pandas.DataFrame'>
RangeIndex: 2457 entries, 0 to 2456
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_reserva         2457 non-null   int64
 1   id_unidade         2457 non-null   int64
 2   id_tipo_quarto     2457 non-null   int64
 3   id_cliente         2457 non-null   int64
 4   id_canal           2345 non-null   float64
 5   data_checkin       2457 non-null   str
 6   data_checkout      2457 non-null   str
 7   qtd_diarias        2457 non-null   int64
 8   num_hospedes       2457 non-null   int64
 9   avaliacao_hospede  2120 non-null   float64
 10  status_reserva     2457 non-null   str
 11  forma_pagamento    2457 non-null   str
dtypes: float64(2), int64(6), str(4)
memory usage: 230.5 KB

In [9]:
df_reserva = pd.concat([df_res, df_reser], ignore_index=True)
df_reserva

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,Confirmada,Cartão De Crédito
1,2,5,1,261,4.0,2023-09-28,2023-01-10,3,2,1.0,Concluída,Pix
2,3,10,4,49,4.0,2023-01-08,2023-06-08,5,1,9.0,Concluída,Cartão De Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,Cancelada,Pix
4,5,7,1,42,1.0,2023-12-01,2023-01-19,7,1,6.0,Confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
4659,3198,7,5,268,1.0,2026-08-05,2026-08-07,2,2,9.0,confirmada,Cartão de Débito
4660,3490,9,3,48,1.0,2026-05-24,2026-05-26,2,3,8.0,CONFIRMADA,Transferência
4661,4579,13,6,306,4.0,2026-04-16,2026-04-18,2,4,NaN,confirmada,Dinheiro
4662,3882,11,1,100,4.0,2025-01-03,2025-01-06,3,1,8.0,CONFIRMADA,CD
4663,4183,3,1,102,1.0,2025-11-07,2025-11-09,2,1,3.0,confirmada,PIX

In [10]:

df_reserva

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,Confirmada,Cartão De Crédito
1,2,5,1,261,4.0,2023-09-28,2023-01-10,3,2,1.0,Concluída,Pix
2,3,10,4,49,4.0,2023-01-08,2023-06-08,5,1,9.0,Concluída,Cartão De Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,Cancelada,Pix
4,5,7,1,42,1.0,2023-12-01,2023-01-19,7,1,6.0,Confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
4659,3198,7,5,268,1.0,2026-08-05,2026-08-07,2,2,9.0,confirmada,Cartão de Débito
4660,3490,9,3,48,1.0,2026-05-24,2026-05-26,2,3,8.0,CONFIRMADA,Transferência
4661,4579,13,6,306,4.0,2026-04-16,2026-04-18,2,4,NaN,confirmada,Dinheiro
4662,3882,11,1,100,4.0,2025-01-03,2025-01-06,3,1,8.0,CONFIRMADA,CD
4663,4183,3,1,102,1.0,2025-11-07,2025-11-09,2,1,3.0,confirmada,PIX

In [11]:
df_reserva.loc[727, 'qtd_diarias'] = 7
df_reserva.loc[954, 'qtd_diarias'] = 4
df_reserva.loc[1133, 'qtd_diarias'] = 3
df_reserva.loc[1151, 'qtd_diarias'] = 2
df_reserva.loc[1447, 'qtd_diarias'] = 6
df_reserva.loc[1580, 'qtd_diarias'] = 4
df_reserva.loc[2311, 'qtd_diarias'] = 4
df_reserva.loc[2383, 'qtd_diarias'] = 2
df_reserva.loc[2383, 'qtd_diarias'] = 2
df_reserva.loc[2383, 'qtd_diarias'] = 2
df_reserva.loc[2383, 'qtd_diarias'] = 2
df_reserva.loc[2383, 'qtd_diarias'] = 2
df_reserva.loc[2567, 'qtd_diarias'] = 1
df_reserva.loc[3135, 'qtd_diarias'] = 1
df_reserva.loc[3193, 'qtd_diarias'] = 1
df_reserva.loc[4468, 'qtd_diarias'] = 1

In [ ]:
df_reserva.loc[df_reserva['id_reserva'] == 4030, 'qtd_diarias'] = 1

In [17]:
df_reserva.loc[(df_reserva['id_reserva'] == 4030)]

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
4545,4030,12,2,41,2.0,2026-08-31,2026-09-01,1,2,9.0,Confirmada,Cartão de Crédito

In [ ]:

df_reserva.iloc[727, :]
df_reserva.iloc[954, :]
df_reserva.iloc[1133, :]
df_reserva.iloc[1151, :]
df_reserva.iloc[1447, :]
df_reserva.iloc[1580, :]
df_reserva.iloc[2311, :]
df_reserva.iloc[2383, :]

id_reserva                 2384
id_unidade                    5
id_tipo_quarto                2
id_cliente                   64
id_canal                    2.0
data_checkin         2024-01-10
data_checkout        2024-03-10
qtd_diarias                   2
num_hospedes                  2
avaliacao_hospede           4.0
status_reserva        Concluída
forma_pagamento        Dinheiro
Name: 2383, dtype: object

In [25]:
df_reserva.loc[df_reserva['id_reserva'] == 37, 'avaliacao_hospede'] = 1
df_reserva.loc[df_reserva['id_reserva'] == 902, 'avaliacao_hospede'] = 1
df_reserva.loc[df_reserva['id_reserva'] == 2073, 'avaliacao_hospede'] = 1
df_reserva.loc[df_reserva['id_reserva'] == 933, 'avaliacao_hospede'] = 3
df_reserva.loc[df_reserva['id_reserva'] == 1718, 'avaliacao_hospede'] = 3
df_reserva.loc[df_reserva['id_reserva'] == 2167, 'avaliacao_hospede'] = 3
df_reserva.loc[df_reserva['id_reserva'] == 3541, 'avaliacao_hospede'] = 1
df_reserva.loc[df_reserva['id_reserva'] == 2874, 'avaliacao_hospede'] = 1
df_reserva.loc[df_reserva['id_reserva'] == 4127, 'avaliacao_hospede'] = 1
df_reserva.loc[df_reserva['id_reserva'] == 4088, 'avaliacao_hospede'] = 3
df_reserva.loc[df_reserva['id_reserva'] == 568, 'num_hospedes'] = 1
df_reserva.loc[df_reserva['id_reserva'] == 675, 'num_hospedes'] = 2
df_reserva.loc[df_reserva['id_reserva'] == 903, 'num_hospedes'] = 1
df_reserva.loc[df_reserva['id_reserva'] == 1201, 'num_hospedes'] = 2
df_reserva.loc[df_reserva['id_reserva'] == 1883, 'num_hospedes'] = 2
df_reserva.loc[df_reserva['id_reserva'] == 2427, 'num_hospedes'] = 2
df_reserva.loc[df_reserva['id_reserva'] == 4463, 'num_hospedes'] = 1
df_reserva.loc[df_reserva['id_reserva'] == 4506, 'num_hospedes'] = 2
df_reserva.loc[df_reserva['id_reserva'] == 4040, 'num_hospedes'] = 2
df_reserva.loc[df_reserva['id_reserva'] == 2687, 'num_hospedes'] = 2

In [33]:
import numpy as np


df_reserva.loc[df_reserva['id_reserva'] == 194, 'avaliacao_hospede'] = np.nan
df_reserva.loc[df_reserva['id_reserva'] == 1538, 'avaliacao_hospede'] = np.nan
df_reserva.loc[df_reserva['id_reserva'] == 1866, 'avaliacao_hospede'] = np.nan
df_reserva.loc[df_reserva['id_reserva'] == 2210, 'avaliacao_hospede'] = np.nan
df_reserva.loc[(df_reserva['id_reserva'] == 1866)]

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
1865,1866,7,3,263,4.0,2024-07-04,2024-09-04,2,2,NaN,Concluída,Dinheiro

In [34]:
df_reserva['data_checkout'] = pd.to_datetime(
    df_reserva['data_checkout'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)
df_reserva['data_checkin'] = pd.to_datetime(
    df_reserva['data_checkin'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

df_reserva['status_reserva'] = df_reserva['status_reserva'].str.strip().str.title()
df_reserva['forma_pagamento'] = df_reserva['forma_pagamento'].str.strip().str.title()
df_reserva.info()

<class 'pandas.DataFrame'>
RangeIndex: 4664 entries, 0 to 4663
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_reserva         4664 non-null   int64
 1   id_unidade         4664 non-null   int64
 2   id_tipo_quarto     4664 non-null   int64
 3   id_cliente         4664 non-null   int64
 4   id_canal           4455 non-null   float64
 5   data_checkin       4664 non-null   datetime64[us]
 6   data_checkout      4664 non-null   datetime64[us]
 7   qtd_diarias        4664 non-null   int64
 8   num_hospedes       4664 non-null   int64
 9   avaliacao_hospede  4014 non-null   float64
 10  status_reserva     4664 non-null   str
 11  forma_pagamento    4664 non-null   str
dtypes: datetime64[us](2), float64(2), int64(6), str(2)
memory usage: 437.4 KB

In [35]:
print (df_reserva['status_reserva'].sort_values().unique())
print(df_reserva['forma_pagamento'].sort_values().unique())

<StringArray>
[   'Cancel.',  'Cancelada',  'Concluida',  'Concluída',      'Conf.',
 'Confirmada',    'No-Show']
Length: 7, dtype: str
<StringArray>
[       'C. Crédito',    'Cartao Credito',     'Cartao Debito',
 'Cartão De Crédito',  'Cartão De Débito',              'Cash',
                'Cc',                'Cd',              'Cred',
          'Dinheiro',               'Déb',               'Pix',
               'Ted',     'Transferencia',     'Transferência']
Length: 15, dtype: str

In [36]:
rese = {
    'Cancel.':                'Cancelada',
    'Concluida':                  'Concluída',
    'Conf.':                   'Confirmada'
    }
df_reserva['status_reserva'] = df_reserva['status_reserva'].map(rese).fillna(df_reserva['status_reserva'])

print('Após mapeamento:')
print(sorted(df_reserva['status_reserva'].unique()))

df_reserva

Após mapeamento:
['Cancelada', 'Concluída', 'Confirmada', 'No-Show']

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,Confirmada,Cartão De Crédito
1,2,5,1,261,4.0,2023-09-28,2023-10-01,3,2,1.0,Concluída,Pix
2,3,10,4,49,4.0,2023-08-01,2023-08-06,5,1,9.0,Concluída,Cartão De Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,Cancelada,Pix
4,5,7,1,42,1.0,2023-01-12,2023-01-19,7,1,6.0,Confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
4659,3198,7,5,268,1.0,2026-05-08,2026-07-08,2,2,9.0,Confirmada,Cartão De Débito
4660,3490,9,3,48,1.0,2026-05-24,2026-05-26,2,3,8.0,Confirmada,Transferência
4661,4579,13,6,306,4.0,2026-04-16,2026-04-18,2,4,NaN,Confirmada,Dinheiro
4662,3882,11,1,100,4.0,2025-03-01,2025-06-01,3,1,8.0,Confirmada,Cd
4663,4183,3,1,102,1.0,2025-07-11,2025-09-11,2,1,3.0,Confirmada,Pix

In [37]:
forma = {
    'C. Crédito':                'Cartão De Crédito',
    'Cartao Credito':            'Cartão De Crédito',
    'Cred':                      'Cartão De Crédito',
    'Cc':                        'Cartão De Crédito',
    'Cartao Debito':             'Cartão De Débito',
    'Cd':                        'Cartão De Débito',
    'Déb':                       'Cartão De Débito',
    'Cash':                      'Dinheiro',
    'Ted':                       'Transferência',
    'Transferencia':             'Transferência'

    }
df_reserva['forma_pagamento'] = df_reserva['forma_pagamento'].map(forma).fillna(df_reserva['forma_pagamento'])

print('Após mapeamento:')
print(sorted(df_reserva['forma_pagamento'].unique()))

df_reserva

Após mapeamento:
['Cartão De Crédito', 'Cartão De Débito', 'Dinheiro', 'Pix', 'Transferência']

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,Confirmada,Cartão De Crédito
1,2,5,1,261,4.0,2023-09-28,2023-10-01,3,2,1.0,Concluída,Pix
2,3,10,4,49,4.0,2023-08-01,2023-08-06,5,1,9.0,Concluída,Cartão De Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,Cancelada,Pix
4,5,7,1,42,1.0,2023-01-12,2023-01-19,7,1,6.0,Confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
4659,3198,7,5,268,1.0,2026-05-08,2026-07-08,2,2,9.0,Confirmada,Cartão De Débito
4660,3490,9,3,48,1.0,2026-05-24,2026-05-26,2,3,8.0,Confirmada,Transferência
4661,4579,13,6,306,4.0,2026-04-16,2026-04-18,2,4,NaN,Confirmada,Dinheiro
4662,3882,11,1,100,4.0,2025-03-01,2025-06-01,3,1,8.0,Confirmada,Cartão De Débito
4663,4183,3,1,102,1.0,2025-07-11,2025-09-11,2,1,3.0,Confirmada,Pix

In [39]:
df_reserva.duplicated().sum()
df_reserva[df_reserva.duplicated(keep=False)]
df_reserva.duplicated(subset=['id_reserva',	'id_unidade',	'id_tipo_quarto',	'id_cliente',	'id_canal',	'data_checkin',	'data_checkout',	'qtd_diarias', 'num_hospedes',	'avaliacao_hospede',	'status_reserva',	'forma_pagamento' ]).sum()

np.int64(15)

In [41]:
df_reserva = df_reserva.drop_duplicates()
df_reserva.duplicated().sum()

np.int64(0)

In [42]:
df_reserva.duplicated().sum()

np.int64(0)

In [ ]:
df_reserva

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,Confirmada,Cartão De Crédito
1,2,5,1,261,4.0,2023-09-28,2023-10-01,3,2,1.0,Concluída,Pix
2,3,10,4,49,4.0,2023-08-01,2023-08-06,5,1,9.0,Concluída,Cartão De Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,Cancelada,Pix
4,5,7,1,42,1.0,2023-01-12,2023-01-19,7,1,6.0,Confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
4659,3198,7,5,268,1.0,2026-05-08,2026-07-08,2,2,9.0,Confirmada,Cartão De Débito
4660,3490,9,3,48,1.0,2026-05-24,2026-05-26,2,3,8.0,Confirmada,Transferência
4661,4579,13,6,306,4.0,2026-04-16,2026-04-18,2,4,NaN,Confirmada,Dinheiro
4662,3882,11,1,100,4.0,2025-03-01,2025-06-01,3,1,8.0,Confirmada,Cartão De Débito
4663,4183,3,1,102,1.0,2025-07-11,2025-09-11,2,1,3.0,Confirmada,Pix

In [123]:
df_reserva.to_csv('reservas.concat.csv', sep=';', index=False)

concatenado reserva antigo e novo
prenchido e consertado valores
numeros de avaliação transformados em nulo
padronização de escrita

In [72]:
df_funci = pd.read_csv ('funcionarios_novos.csv', sep=';')
df_funci.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  10 non-null     int64
 1   id_unidade      10 non-null     int64
 2   nome            10 non-null     str
 3   cargo           10 non-null     str
 4   departamento    10 non-null     str
 5   salario         9 non-null      str
 6   data_admissao   10 non-null     str
dtypes: int64(2), str(5)
memory usage: 692.0 bytes

In [73]:
df_funci['cargo'] = df_funci['cargo'].str.strip().str.title()
df_funci['cargo'].value_counts()

cargo
Sommelier              2
Analista Financeiro    2
Segurança              2
Concierge              1
Auxiliar De Limpeza    1
Chef De Cozinha        1
Manobrista             1
Name: count, dtype: int64

In [74]:
df_funci['departamento'] = df_funci ['departamento'].str.strip().str.title()
df_funci['departamento'].value_counts()

departamento
Governança    3
A&B           3
Financeiro    2
Operações     2
Name: count, dtype: int64

In [75]:
df_funci['departamento'].value_counts()
dep = {'A&B':                   'Alimentos e Bebidas'}
df_funci['departamento'] = df_funci['departamento'].map(dep).fillna(df_funci['departamento'])

print('Após mapeamento:')
print(sorted(df_funci['departamento'].unique()))

Após mapeamento:
['Alimentos e Bebidas', 'Financeiro', 'Governança', 'Operações']

In [78]:

df_funci['salario'] = (
df_funci['salario']
.str.replace('.', '', regex=False)
.str.replace('"', '', regex=False)
.str.replace(',', '.', regex=False)
.astype(float)
)

In [79]:
df_funci['salario']

0    3987.71
1    2432.01
2    3651.51
3    8545.89
4    9187.66
5    4710.88
6    8932.76
7        NaN
8    2782.48
9    8289.01
Name: salario, dtype: float64

In [88]:
df_funci['data_admissao'] = pd.to_datetime(
    df_funci['data_admissao'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)
df_funci.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  10 non-null     int64
 1   id_unidade      10 non-null     int64
 2   nome            10 non-null     str
 3   cargo           10 non-null     str
 4   departamento    10 non-null     str
 5   salario         9 non-null      float64
 6   data_admissao   10 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 692.0 bytes

In [84]:
df_funci.to_csv('funcionarios_novos.csv', sep=';', index=False)
df_funci

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,135,13,Marcos Andrade,Concierge,Governança,3987.71,2024-05-22
1,136,13,Fernanda Lopes,Sommelier,Governança,2432.01,2024-05-04
2,137,13,Ricardo Nunes,Sommelier,Alimentos e Bebidas,3651.51,2025-12-07
3,138,13,Patrícia Melo,Analista Financeiro,Alimentos e Bebidas,8545.89,2024-12-06
4,139,13,Bruno Cardoso,Auxiliar De Limpeza,Financeiro,9187.66,2024-10-12
5,140,13,Camila Ferreira,Segurança,Governança,4710.88,2024-09-27
6,141,13,Diego Ramos,Analista Financeiro,Alimentos e Bebidas,8932.76,2024-03-21
7,142,13,Juliana Prado,Chef De Cozinha,Operações,NaN,2024-12-03
8,143,13,Leonardo Vaz,Manobrista,Operações,2782.48,2024-08-26
9,144,13,Renata Castro,Segurança,Financeiro,8289.01,2024-06-15

padronizado nomes
convertido salario para float 
salvo funcionario novos

In [ ]:
df_funcionarios = pd.concat([df_fun, df_funci], ignore_index=True)
df_funcionarios
 sep=';', index=False)

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar De Limpeza,Governança,2139.00,2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,1746.00,2021-12-29
2,3,1,Sara Teixeira,Analista Financeiro,Financeiro,5356.00,2022-03-01
3,4,1,Julia Monteiro,Auxiliar De Limpeza,Governança,2070.00,2019-06-10
4,5,1,Daniela Ramos,Auxiliar De Limpeza,Governança,1572.00,2018-10-16
...,...,...,...,...,...,...,...
139,140,13,Camila Ferreira,Segurança,Governança,4710.88,2024-09-27
140,141,13,Diego Ramos,Analista Financeiro,Alimentos e Bebidas,8932.76,2024-03-21
141,142,13,Juliana Prado,Chef De Cozinha,Operações,NaN,2024-12-03
142,143,13,Leonardo Vaz,Manobrista,Operações,2782.48,2024-08-26
143,144,13,Renata Castro,Segurança,Financeiro,8289.01,2024-06-15

In [114]:
df_funcionarios.loc[df_funcionarios['id_funcionario'] == 142, 'salario'] = 7850
df_funcionarios.loc[(df_funcionarios['id_funcionario'] == 142)]

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
141,142,13,Juliana Prado,Chef De Cozinha,Operações,7850.0,2024-12-03

In [116]:
display(df_funcionarios.describe(include='object'))
df_funcionarios.info()

C:\Users\eduar\AppData\Local\Temp\ipykernel_11312\2671057528.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df_funcionarios.describe(include='object'))

                nome       cargo departamento
count            144         144          144
unique            55          12            8
top     Ursula Pinto  Manutenção   Governança
freq               8          24           41

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  144 non-null    int64
 1   id_unidade      144 non-null    int64
 2   nome            144 non-null    str
 3   cargo           144 non-null    str
 4   departamento    144 non-null    str
 5   salario         144 non-null    float64
 6   data_admissao   144 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 8.0 KB

In [121]:
df_funcionarios.duplicated().sum()
df_funcionarios[df_funcionarios.duplicated(keep=False)]
df_funcionarios.duplicated(subset=['id_funcionario',	'id_unidade',	'nome',	'cargo',	'departamento',	'salario',	'data_admissao']).sum()

np.int64(0)

In [184]:
df_funcionarios.to_csv('funcionarios.concat.csv', sep=';', ignore_index=True)
df_funcionarios

TypeError: NDFrame.to_csv() got an unexpected keyword argument 'ignore_index'

concatenado funcionários
salários consertados

In [140]:
df_clien = pd.read_csv('clientes_novos.csv', sep=';')
df_clien

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,301,Alexandre Bittencourt,Lisboa,EX,36-45,Corporativo
1,302,Beatriz Falcão,Belo Horizonte,MG,26-35,Pessoa Física
2,303,Caio Serpa,Belo Horizonte,MG,36-45,PJ
3,304,Débora Vasconcelos,Miami,EX,NaN,PF
4,305,Eduardo Mourão,Buenos Aires,EX,46-55,Pessoa Jurídica
5,306,Fabiana Restier,Porto Alegre,rs,46-55,PF
6,307,Gustavo Peixoto,Nova York,EX,56-65,Pessoa Jurídica
7,308,Helena Quintela,Brasília,DF,36-45,PJ
8,309,Igor Salgado,Brasília,DF,56-65,Pessoa Jurídica
9,310,Joana Villar,Porto Alegre,RS,36-45,PJ
10,311,Kleber Andrade Neto,Curitiba,PR,26-35,Pessoa Jurídica
11,312,Larissa Monteverde,São Paulo,SP,26-35,Corporativo
12,313,Marcelo Trindade,Rio de Janeiro,RJ,26-35,PF
13,314,Natália Ferraz,Brasília,DF,46-55,PF
14,315,Otávio Camargo,Nova York,EX,26-35,PJ
15,316,Priscila Guimarães,Lisboa,EX,NaN,PF
16,317,Rodrigo Vasques,Rio de Janeiro,RJ,36-45,PF
17,318,Sabrina Leitão,Brasília,DF,46-55,PF
18,319,Thiago Bicalho,Belo Horizonte,MG,46-55,Pessoa Jurídica
19,320,Vivian Lacerda,Buenos Aires,EX,56-65,Pessoa Jurídica

In [ ]:

df_clien['cidade_origem'].sort_values().unique()
df_clien['estado_origem'].sort_values()
print(sorted(df_clien['cidade_origem'].unique()))
print(sorted(df_clien['estado_origem'].unique()))

['Belo Horizonte', 'Brasília', 'Buenos Aires', 'Curitiba', 'Lisboa', 'Miami', 'Nova York', 'Porto Alegre', 'Rio de Janeiro', 'São Paulo']
['DF', 'EX', 'MG', 'PR', 'RJ', 'RS', 'SP', 'rs']

In [145]:
df_clien[df_clien.isnull().any(axis=1)]

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
3,304,Débora Vasconcelos,Miami,EX,NaN,PF
15,316,Priscila Guimarães,Lisboa,EX,NaN,PF

In [144]:
mapa_cidades = {
    'rs': 'RS',
}

df_clien['estado_origem'] = df_clien['estado_origem'].map(mapa_cidades).fillna(df_clien['estado_origem'])

print('Após mapeamento:')
print(sorted(df_clien['estado_origem'].unique()))

Após mapeamento:
['DF', 'EX', 'MG', 'PR', 'RJ', 'RS', 'SP']

In [146]:
print(sorted(df_clien['tipo_cliente'].unique()))

['Corporativo', 'PF', 'PJ', 'Pessoa Física', 'Pessoa Jurídica']

In [154]:
tipo = {
    'PF':   'Pessoa Física',
    'Pessoa Jurídica':  'Corporativo',
    'PJ':   'Corporativo',
    'CorporativoPJCorporativo': 'Corporativo'
}

df_clien['tipo_cliente'] = df_clien['tipo_cliente'].map(tipo).fillna(df_clien['tipo_cliente'])

print('Após mapeamento:')
print(sorted(df_clien['tipo_cliente'].unique()))

Após mapeamento:
['Corporativo', 'Pessoa Física']

In [185]:
df_clien.to_csv('clientes_novos.csv',sep=';', index=False )

padronizado tipo de cliente 
padronizado estado

In [187]:

df_cliente = pd.concat([df_cli, df_clien], ignore_index=True)
df_cliente

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,Corporativo
1,2,Larissa Sousa,Curitiba,PR,18-25,Pessoa Física
2,3,Tatiana Coelho,Rio de Janeiro,RJ,65+,Corporativo
3,4,Wilson Duarte,Brasília,DF,26-35,Corporativo
4,5,Gabriela Lima,Rio de Janeiro,RJ,46-55,Pessoa Física
...,...,...,...,...,...,...
316,316,Priscila Guimarães,Lisboa,EX,NaN,Pessoa Física
317,317,Rodrigo Vasques,Rio de Janeiro,RJ,36-45,Pessoa Física
318,318,Sabrina Leitão,Brasília,DF,46-55,Pessoa Física
319,319,Thiago Bicalho,Belo Horizonte,MG,46-55,Corporativo
320,320,Vivian Lacerda,Buenos Aires,EX,56-65,Corporativo

In [189]:
df_cliente.to_csv('clientes.concat.csv', sep=';', index=False)
df_cliente

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,Corporativo
1,2,Larissa Sousa,Curitiba,PR,18-25,Pessoa Física
2,3,Tatiana Coelho,Rio de Janeiro,RJ,65+,Corporativo
3,4,Wilson Duarte,Brasília,DF,26-35,Corporativo
4,5,Gabriela Lima,Rio de Janeiro,RJ,46-55,Pessoa Física
...,...,...,...,...,...,...
316,316,Priscila Guimarães,Lisboa,EX,NaN,Pessoa Física
317,317,Rodrigo Vasques,Rio de Janeiro,RJ,36-45,Pessoa Física
318,318,Sabrina Leitão,Brasília,DF,46-55,Pessoa Física
319,319,Thiago Bicalho,Belo Horizonte,MG,46-55,Corporativo
320,320,Vivian Lacerda,Buenos Aires,EX,56-65,Corporativo