In [22]:
import pandas as pd 
import numpy as np

CSV CANAIS DE VENDA

(p)coluna canal de venda tem 'ota' o que seria?
(t)coluna comissão pct esta em str


CSV CLIENTE

(t) clientes duplicados (3?)
(p) temos clientes com todas as informações idênticas salvo coluna de estado de origem 

(t) coluna de tipo de cliente precisa ser padroni.
(p) NaN existente, não deveria constar como nulo?
(t) coluna estado de origem tem que ser padroni.
(p) coluna faixa_etaria com muito NaN PERGUNTA DE NEGOCIO, É IMPORTANTE PARA A LEITURA DO NEGOCIO


CSV FUNCIONARIO

(t) Coluna salatio str
(p) coluna salario 6 NaN IMPORTANTE PARA A LEITURA?
(t) leta maiuscula na coluna cargo


CSV RESERVAS

(t) Coluna status reserva precisa ser padronizado
(t) NaN na coluna id_canal e avaliação_ cliente IMPORTANTE PARA LEITURA
(t) Coluna forma de pagamento precisa padronizar

CSV tipos quarto

(t) coluna valor diaria base como str


CSV UNIDADES

(t) regiao precisa padronizar espaço no serra
(t) categoria hotel padronizar, nome ext. str
(t) padronizar nome das regiões, csv conta com: Capital, Serra, capital, CAP,Baixada Fluminense, Baixada fluminense,Serra           
(t) numero de quartos esta float precisa ir para int
(p) número de quarto em Paraty e Petrópolis

In [30]:
pd.read_csv ('canais_venda.csv', sep=';')
pd.read_csv ('clientes.csv', sep=';')
pd.read_csv ('funcionarios.csv', sep=';')
pd.read_csv ('reservas.csv', sep=';')
pd.read_csv ('tipos_quarto.csv', sep=';')
pd.read_csv ('unidades.csv', sep=';')

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5 estrelas,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,capital,4 estrelas,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3*,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,CAP,4 estrelas,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,Três Estrelas,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada fluminense,3 estrelas,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5 estrelas,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 estrelas,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,cinco estrelas,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 estrelas,50.0

In [31]:
df = pd.read_csv('unidades.csv', sep=';')

print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

(12, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5 estrelas,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,capital,4 estrelas,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3*,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,CAP,4 estrelas,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,Três Estrelas,50.0

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 estrelas,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,cinco estrelas,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 estrelas,50.0

id_unidade             int64
nome_unidade             str
cidade                   str
regiao                   str
categoria_hotel          str
num_quartos_total    float64
dtype: object

In [34]:
df['categoria_hotel'].value_counts()

categoria_hotel
4 estrelas        4
5 estrelas        3
3*                1
Três Estrelas     1
3 estrelas        1
4 Estrelas        1
cinco estrelas    1
Name: count, dtype: int64

In [ ]:
df[df.duplicated(subset=['num_quartos_total'], keep=False)]

In [36]:
df[df.isnull().any(axis=1)]

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5 estrelas,NaN
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN

In [37]:
df['categoria_hotel'].value_counts()

categoria_hotel
4 estrelas        4
5 estrelas        3
3*                1
Três Estrelas     1
3 estrelas        1
4 Estrelas        1
cinco estrelas    1
Name: count, dtype: int64

In [39]:
mapa = {
    '4 estrelas':                '4',
    '4 Estrelas':                '4',
    '3*':                        '3',
    'Três Estrelas':             '3',
    '3 estrelas':               '3',
    '5 estrelas':                '5',
    'cinco estrelas':            '5'
}
df['categoria_hotel'] = df['categoria_hotel'].map(mapa).fillna(df['categoria_hotel'])

print('Após mapeamento:')
print(sorted(df['categoria_hotel'].unique()))

Após mapeamento:
['3', '4', '5']

categoria_hotel
4    5
5    4
3    3
Name: count, dtype: int64

In [40]:
df['categoria_hotel'].value_counts()

categoria_hotel
4    5
5    4
3    3
Name: count, dtype: int64

In [ ]:
df

In [42]:
df['regiao'].value_counts()

regiao
Costa Verde           3
Capital               2
Serra                 2
capital               1
CAP                   1
Baixada Fluminense    1
Baixada fluminense    1
Serra                 1
Name: count, dtype: int64

In [43]:
reg = {
    'capital':                'Capital',
    'CAP':                  'Capital',
    'Serra':                   'Serra',
     'Baixada fluminense':             'Baixada Fluminense'
}
df['regiao'] = df['regiao'].map(reg).fillna(df['regiao'])

print('Após mapeamento:')
print(sorted(df['regiao'].unique()))

Após mapeamento:
['Baixada Fluminense', 'Capital', 'Costa Verde', 'Serra', 'Serra ']

In [45]:
df['regiao'] = df['regiao'].str.strip().str.title()
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50.0

In [ ]:
df['num_quartos_total'] = df['num_quartos_total'].astype("Int64")
df

In [50]:
df = df.rename(columns={'categoria_hotel': 'categoria_hotel(estrelas)'})
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [52]:
df['categoria_hotel(estrelas)'] = pd.to_numeric(df['categoria_hotel(estrelas)'], errors="coerce").astype("Int64")
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [57]:
df.to_csv('unidades.csv', sep=';', index=False)
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50



CSV UNIDADES

(t) padronizado categoria hotel, deixados apenas números, 
(t) padronizado nome das regiões: Capital, Serra, Baixada Fluminense, Costa Verde           
(t) numero de quartos esta float precisa ir para int
(p) número de quarto em Paraty e Petrópolis

In [ ]:
df_tipo = pd.read_csv('tipos_quarto.csv', sep=';')

print(df_tipo.shape)
display(df_tipo.head())
display(df_tipo.tail())
display(df_tipo.dtypes)

(6, 4)

   id_tipo_quarto     descricao  capacidade_max valor_diaria_base
0               1      STANDARD               2         R$ 280,00
1               2     superior                2         R$ 420,00
2               3        Deluxe               3         R$ 580,00
3               4         Suite               4         R$ 950,00
4               5  Suíte Master               4       R$ 1.500,00

   id_tipo_quarto     descricao  capacidade_max valor_diaria_base
1               2     superior                2         R$ 420,00
2               3        Deluxe               3         R$ 580,00
3               4         Suite               4         R$ 950,00
4               5  Suíte Master               4       R$ 1.500,00
5               3        Deluxe               3         R$ 580,00

id_tipo_quarto       int64
descricao              str
capacidade_max       int64
valor_diaria_base      str
dtype: object

In [58]:
df_tipo['descricao'] = df_tipo['descricao'].str.strip().str.title()
df_tipo

   id_tipo_quarto     descricao  capacidade_max valor_diaria_base
0               1      Standard               2         R$ 280,00
1               2      Superior               2         R$ 420,00
2               3        Deluxe               3         R$ 580,00
3               4         Suite               4         R$ 950,00
4               5  Suíte Master               4       R$ 1.500,00
5               3        Deluxe               3         R$ 580,00

In [ ]:
df_tipo['valor_diaria_base'] = (
df_tipo['valor_diaria_base']
.str.replace('R$', '', regex=False)
.str.replace(' ', '', regex=False)
.str.replace('.', '', regex=False) # remove separador de milhar
.str.replace(',', '.', regex=False)
.astype(float)
)

In [84]:
df_tipo.to_csv('tipos_quarto.csv', sep=';', index=False)

In [85]:
df_tipo

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
0               1      Standard               2              280.0
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0
5               3        Deluxe               3              580.0

padronizado a escrita da couna 'descrição'
coluna 'valor_diaria_base'

In [89]:
df_res = pd.read_csv('reservas.csv', sep=';')

print(df_res.shape)
display(df_res.head())
display(df_res.tail())
display(df_res.dtypes)

(2457, 12)

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,confirmada,Cartão de Crédito
1,2,5,1,261,4.0,2023-09-28,2023-10-01,3,2,1.0,concluída,PIX
2,3,10,4,49,4.0,2023-08-01,2023-08-06,5,1,9.0,concluída,Cartão de Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,cancelada,PIX
4,5,7,1,42,1.0,2023-01-12,2023-01-19,7,1,6.0,confirmada,Transferência

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
2452,2453,10,3,210,4.0,2023-10-22,2023-10-27,5,1,9.0,confirmada,Cartão de Débito
2453,2454,7,3,271,2.0,2024-08-08,2024-08-14,6,2,6.0,confirmada,PIX
2454,2455,7,1,143,1.0,2023-07-26,2023-07-27,1,2,6.0,confirmada,Transferência
2455,2456,8,4,176,1.0,2023-05-10,2023-05-17,7,1,6.0,concluída,Cartão de Débito
2456,2457,6,3,160,1.0,2023-07-01,2023-07-05,4,1,9.0,confirmada,Cartão de Crédito

id_reserva             int64
id_unidade             int64
id_tipo_quarto         int64
id_cliente             int64
id_canal             float64
data_checkin             str
data_checkout            str
qtd_diarias            int64
num_hospedes           int64
avaliacao_hospede    float64
status_reserva           str
forma_pagamento          str
dtype: object

In [94]:
df_res['data_checkin'] = pd.to_datetime(
    df_res['data_checkin'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [97]:
df_res['data_checkout'] = pd.to_datetime(
    df_res['data_checkout'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [ ]:

display(df_res.dtypes)
df_res

In [109]:
df_res['status_reserva'] = df_res['status_reserva'].str.strip().str.title()
df_res['forma_pagamento'] = df_res['forma_pagamento'].str.strip().str.title()

In [110]:
df_tipo.to_csv('reservas.csv', sep=';', index=False)
df_res

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,Confirmada,Cartão De Crédito
1,2,5,1,261,4.0,2023-09-28,2023-01-10,3,2,1.0,Concluída,Pix
2,3,10,4,49,4.0,2023-01-08,2023-06-08,5,1,9.0,Concluída,Cartão De Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,Cancelada,Pix
4,5,7,1,42,1.0,2023-12-01,2023-01-19,7,1,6.0,Confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
2452,2453,10,3,210,4.0,2023-10-22,2023-10-27,5,1,9.0,Confirmada,Cartão De Débito
2453,2454,7,3,271,2.0,2024-08-08,2024-08-14,6,2,6.0,Confirmada,Pix
2454,2455,7,1,143,1.0,2023-07-26,2023-07-27,1,2,6.0,Confirmada,Transferência
2455,2456,8,4,176,1.0,2023-10-05,2023-05-17,7,1,6.0,Concluída,Cartão De Débito
2456,2457,6,3,160,1.0,2023-01-07,2023-05-07,4,1,9.0,Confirmada,Cartão De Crédito

alterado para datetime data checkin e checkout
nome com letra maisúcula status reserva e forma de pagamento

In [113]:
df_fun = pd.read_csv('funcionarios.csv', sep=';')
df_fun

print(df_fun.shape)
display(df_fun.head())
display(df_fun.tail())
display(df_fun.dtypes)

(134, 7)

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar de Limpeza,Governança,"""2.139,00""",2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,"""1.746,00""",2021-12-29
2,3,1,Sara Teixeira,analista financeiro,Financeiro,"""5.356,00""",2022-03-01
3,4,1,Julia Monteiro,Auxiliar de Limpeza,Governança,"""2.070,00""",2019-06-10
4,5,1,Daniela Ramos,Auxiliar de Limpeza,Governança,"""1.572,00""",2018-10-16

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
129,130,12,Fernanda Cruz,Manutenção,Manutenção,"""2.221,00""",2020-08-16
130,131,12,Abel Correia,Gerente,Administração,"""8.404,00""",2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,"""2.700,00""",2021-01-22
132,133,12,Yuri Castro,segurança,Segurança,"""1.976,00""",2021-10-08
133,134,12,Eduardo Lopes,Recepcionista,Recepção,"""2.442,00""",2023-02-17

id_funcionario    int64
id_unidade        int64
nome                str
cargo               str
departamento        str
salario             str
data_admissao       str
dtype: object

In [116]:
df_fun['cargo'] = df_fun['cargo'].str.strip().str.title()

In [ ]:
df_fun['cargo'].value_counts()

In [ ]:
df_fun['departamento'].value_counts()

In [120]:
dep = {
    'Gov.':                'Governança',
    'Admin.':                  'Administração',
    'A&B':                   'Alimentos e Bebidas',
     'Baixada fluminense':             'Baixada Fluminense'
}
df_fun['departamento'] = df_fun['departamento'].map(dep).fillna(df_fun['departamento'])

print('Após mapeamento:')
print(sorted(df_fun['departamento'].unique()))

Após mapeamento:
['Administração', 'Alimentos e Bebidas', 'Financeiro', 'Governança', 'Manutenção', 'Recepção', 'Segurança']

In [124]:
df_fun['salario'] = (
df_fun['salario']
.str.replace('.', '', regex=False)
.str.replace('"', '', regex=False)
.str.replace(',', '.', regex=False)
.astype(float)
)

In [127]:
df_fun['data_admissao'] = pd.to_datetime(
    df_fun['data_admissao'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [132]:
display(df_fun.dtypes)
df_fun.to_csv('funcionarios.csv', sep=';', index=False)
df_fun

id_funcionario             int64
id_unidade                 int64
nome                         str
cargo                        str
departamento                 str
salario                  float64
data_admissao     datetime64[us]
dtype: object

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar De Limpeza,Governança,2139.0,2020-05-10
1,2,1,Abel Correia,Segurança,Segurança,1746.0,2021-12-29
2,3,1,Sara Teixeira,Analista Financeiro,Financeiro,5356.0,2022-01-03
3,4,1,Julia Monteiro,Auxiliar De Limpeza,Governança,2070.0,2019-10-06
4,5,1,Daniela Ramos,Auxiliar De Limpeza,Governança,1572.0,2018-10-16
...,...,...,...,...,...,...,...
129,130,12,Fernanda Cruz,Manutenção,Manutenção,2221.0,2020-08-16
130,131,12,Abel Correia,Gerente,Administração,8404.0,2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,2700.0,2021-01-22
132,133,12,Yuri Castro,Segurança,Segurança,1976.0,2021-08-10
133,134,12,Eduardo Lopes,Recepcionista,Recepção,2442.0,2023-02-17

padronizado escrita cargo, com letras maisuculas
padronizado departamento tirado abreviações
sálario padronizado para float e retirado datas
data admissao para datetime

In [136]:
df_cli = pd.read_csv ('clientes.csv', sep=';')
df_cli
print(df_cli.shape)
display(df_cli.head())
display(df_cli.tail())
display(df_cli.dtypes)

(301, 6)

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,PJ
1,2,Larissa Sousa,Curitiba,SC,18-25,pessoa fisica
2,3,Tatiana Coelho,Rio de Janeiro,CE,65+,Corporativo
3,4,Wilson Duarte,Brasília,AM,26-35,corporativo
4,5,Gabriela Lima,Rio de Janeiro,SP,46-55,Pessoa Física

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
296,297,Roberta Leite,Curitiba,DF,56-65,pessoa fisica
297,298,Eduardo Lopes,São Paulo,ES,36-45,PJ
298,299,Vanessa Cavalcanti,Curitiba,AM,46-55,Pessoa Física
299,300,Julia Monteiro,Brasília,PR,36-45,Corporativo
300,47,Carlos Neto,Niterói,RJ,36-45,Corporativo

id_cliente       int64
nome               str
cidade_origem      str
estado_origem      str
faixa_etaria       str
tipo_cliente       str
dtype: object

In [ ]:
df_cli[df_cli.isnull().any(axis=1)]

In [137]:
df_cli['cidade_origem'].sort_values()

258    Belo Horizonte
154    Belo Horizonte
149    Belo Horizonte
44     Belo Horizonte
264    Belo Horizonte
            ...
61          São Paulo
59          São Paulo
263         São Paulo
124         São Paulo
0           São Paulo
Name: cidade_origem, Length: 301, dtype: str

In [138]:
df_cli['estado_origem'].sort_values()

220      AM
284      AM
61       AM
192      AM
286      AM
       ...
102      SP
34       SP
0        SP
288    r.j.
212      rj
Name: estado_origem, Length: 301, dtype: str

In [142]:
print(sorted(df_cli['cidade_origem'].unique()))
print(sorted(df_cli['estado_origem'].unique()))

['Belo Horizonte', 'Brasília', 'Curitiba', 'Fortaleza', 'Niterói', 'Recife', 'Rio de Janeiro', 'Salvador', 'São Paulo']
['AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MG', 'PA', 'PE', 'PR', 'RJ', 'RS', 'Rio de Janeiro', 'SC', 'SP', 'r.j.', 'rj']

In [144]:
mapa_cidades = {
    'r.j.': 'RJ',
    'rj': 'RJ',
    'Rio de Janeiro': 'RJ'
}

df_cli['estado_origem'] = df_cli['estado_origem'].map(mapa_cidades).fillna(df['estado_origem'])

print('Após mapeamento:')
print(sorted(df_cli['estado_origem'].unique()))

KeyError: 'estado_origem'