In [265]:
import pandas as pd 
import numpy as np

CSV CANAIS DE VENDA

(p)coluna canal de venda tem 'ota' o que seria?
(t)coluna comissão pct esta em str


CSV CLIENTE

(t) clientes duplicados (3?)
(p) temos clientes com todas as informações idênticas salvo coluna de estado de origem 

(t) coluna de tipo de cliente precisa ser padroni.
(p) NaN existente, não deveria constar como nulo?
(t) coluna estado de origem tem que ser padroni.
(p) coluna faixa_etaria com muito NaN PERGUNTA DE NEGOCIO, É IMPORTANTE PARA A LEITURA DO NEGOCIO


CSV FUNCIONARIO

(t) Coluna salatio str
(p) coluna salario 6 NaN IMPORTANTE PARA A LEITURA?
(t) leta maiuscula na coluna cargo


CSV RESERVAS

(t) Coluna status reserva precisa ser padronizado
(t) NaN na coluna id_canal e avaliação_ cliente IMPORTANTE PARA LEITURA
(t) Coluna forma de pagamento precisa padronizar

CSV tipos quarto

(t) coluna valor diaria base como str


CSV UNIDADES

(t) regiao precisa padronizar espaço no serra
(t) categoria hotel padronizar, nome ext. str
(t) padronizar nome das regiões, csv conta com: Capital, Serra, capital, CAP,Baixada Fluminense, Baixada fluminense,Serra           
(t) numero de quartos esta float precisa ir para int
(p) número de quarto em Paraty e Petrópolis

In [266]:
pd.read_csv ('canais_venda.csv', sep=';')
pd.read_csv ('clientes.csv', sep=';')
pd.read_csv ('funcionarios.csv', sep=';')
pd.read_csv ('reservas.csv', sep=';')
pd.read_csv ('tipos_quarto.csv', sep=';')
pd.read_csv ('unidades.csv', sep=';')

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,70
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [408]:
df = pd.read_csv('unidades.csv', sep=';')

print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

(12, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5 estrelas,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,capital,4 estrelas,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3*,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,CAP,4 estrelas,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,Três Estrelas,50.0

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 estrelas,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,cinco estrelas,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 estrelas,50.0

id_unidade             int64
nome_unidade             str
cidade                   str
regiao                   str
categoria_hotel          str
num_quartos_total    float64
dtype: object

In [409]:
df[df.duplicated(subset=['num_quartos_total'], keep=False)]

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3*,60.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,Três Estrelas,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada fluminense,3 estrelas,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5 estrelas,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 estrelas,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 estrelas,50.0

In [410]:
df[df.isnull().any(axis=1)]

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5 estrelas,NaN
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN

In [412]:
df['categoria_hotel'].value_counts()

categoria_hotel
4 estrelas        4
5 estrelas        3
3*                1
Três Estrelas     1
3 estrelas        1
4 Estrelas        1
cinco estrelas    1
Name: count, dtype: int64

In [414]:
mapa = {
    '4 estrelas':                '4',
    '4 Estrelas':                '4',
    '3*':                        '3',
    'Três Estrelas':             '3',
    '3 estrelas':               '3',
    '5 estrelas':                '5',
    'cinco estrelas':            '5'
}
df['categoria_hotel'] = df['categoria_hotel'].map(mapa).fillna(df['categoria_hotel'])

print('Após mapeamento:')
print(sorted(df['categoria_hotel'].unique()))

Após mapeamento:
['3', '4', '5']

In [416]:
df['categoria_hotel'].value_counts()

categoria_hotel
4    5
5    4
3    3
Name: count, dtype: int64

In [417]:
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,capital,4,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,CAP,4,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada fluminense,3,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50.0

In [418]:
df['regiao'].value_counts()

regiao
Costa Verde           3
Capital               2
Serra                 2
capital               1
CAP                   1
Baixada Fluminense    1
Baixada fluminense    1
Serra                 1
Name: count, dtype: int64

In [419]:
reg = {
    'capital':                'Capital',
    'CAP':                  'Capital',
    'Serra':                   'Serra',
     'Baixada fluminense':             'Baixada Fluminense'
}
df['regiao'] = df['regiao'].map(reg).fillna(df['regiao'])

print('Após mapeamento:')
print(sorted(df['regiao'].unique()))

Após mapeamento:
['Baixada Fluminense', 'Capital', 'Costa Verde', 'Serra', 'Serra ']

In [420]:
df['regiao'] = df['regiao'].str.strip().str.title()
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50.0

In [421]:
df['num_quartos_total'] = df['num_quartos_total'].astype("Int64")
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [422]:
df = df.rename(columns={'categoria_hotel': 'categoria_hotel(estrelas)'})
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [423]:
df['categoria_hotel(estrelas)'] = pd.to_numeric(df['categoria_hotel(estrelas)'], errors="coerce").astype("Int64")
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [424]:
df.to_csv('unidades.csv', sep=';', index=False)
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50



CSV UNIDADES

(t) padronizado categoria hotel, deixados apenas números, 
(t) padronizado nome das regiões: Capital, Serra, Baixada Fluminense, Costa Verde           
(t) numero de quartos esta float precisa ir para int
(p) número de quarto em Paraty e Petrópolis

In [281]:
df_tipo = pd.read_csv('tipos_quarto.csv', sep=';')

print(df_tipo.shape)
display(df_tipo.head())
display(df_tipo.tail())
display(df_tipo.dtypes)

(6, 4)

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
0               1      Standard               2              280.0
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0
5               3        Deluxe               3              580.0

id_tipo_quarto         int64
descricao                str
capacidade_max         int64
valor_diaria_base    float64
dtype: object

In [282]:
df_tipo['descricao'] = df_tipo['descricao'].str.strip().str.title()
df_tipo

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
0               1      Standard               2              280.0
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0
5               3        Deluxe               3              580.0

In [283]:
df_tipo['valor_diaria_base'] = (
df_tipo['valor_diaria_base']
.str.replace('R$', '', regex=False)
.str.replace(' ', '', regex=False)
.str.replace('.', '', regex=False) # remove separador de milhar
.str.replace(',', '.', regex=False)
.astype(float)
)

AttributeError: Can only use .str accessor with string values, not floating

In [284]:
df_tipo.to_csv('tipos_quarto.csv', sep=';', index=False)

In [285]:
df_tipo

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
0               1      Standard               2              280.0
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0
5               3        Deluxe               3              580.0

padronizado a escrita da couna 'descrição'
coluna 'valor_diaria_base'

In [ ]:
df_res = pd.read_csv('reservas.csv', sep=';')
df_re

print(df_res.shape)
display(df_res.head())
display(df_res.tail())
display(df_res.dtypes)

In [287]:
df_res['data_checkin'] = pd.to_datetime(
    df_res['data_checkin'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [ ]:
df_res['data_checkout'] = pd.to_datetime(
    df_res['data_checkout'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [316]:


print (df_res['status_reserva'].sort_values().unique())


print(df_res['forma_pagamento'].sort_values().unique())

<StringArray>
[   'Cancel.',  'Cancelada',  'Concluida',  'Concluída',      'Conf.',
 'Confirmada',    'No-Show']
Length: 7, dtype: str
<StringArray>
[       'C. Crédito',    'Cartao Credito',     'Cartao Debito',
 'Cartão De Crédito',  'Cartão De Débito',              'Cash',
                'Cc',                'Cd',              'Cred',
          'Dinheiro',               'Déb',               'Pix',
               'Ted',     'Transferencia',     'Transferência']
Length: 15, dtype: str

In [ ]:
rese = {
    'Cancel.':                'Capital',
    'CAP':                  'Capital',
    'Serra':                   'Serra',
     'Baixada fluminense':             'Baixada Fluminense'
}
df['reseiao'] = df['reseiao'].map(rese).fillna(df['regiao'])

print('Após mapeamento:')
print(sorted(df['regiao'].unique()))

In [ ]:

df_res['status_reserva'] = df_res['status_reserva'].str.strip().str.title()
df_res['forma_pagamento'] = df_res['forma_pagamento'].str.strip().str.title()
df_res

In [294]:
df_res.to_csv('reservas.csv', sep=';', index=False)
df_res

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,Confirmada,Cartão De Crédito
1,2,5,1,261,4.0,2023-09-28,2023-01-10,3,2,1.0,Concluída,Pix
2,3,10,4,49,4.0,2023-01-08,2023-06-08,5,1,9.0,Concluída,Cartão De Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,Cancelada,Pix
4,5,7,1,42,1.0,2023-12-01,2023-01-19,7,1,6.0,Confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
2452,2453,10,3,210,4.0,2023-10-22,2023-10-27,5,1,9.0,Confirmada,Cartão De Débito
2453,2454,7,3,271,2.0,2024-08-08,2024-08-14,6,2,6.0,Confirmada,Pix
2454,2455,7,1,143,1.0,2023-07-26,2023-07-27,1,2,6.0,Confirmada,Transferência
2455,2456,8,4,176,1.0,2023-10-05,2023-05-17,7,1,6.0,Concluída,Cartão De Débito
2456,2457,6,3,160,1.0,2023-01-07,2023-05-07,4,1,9.0,Confirmada,Cartão De Crédito

alterado para datetime data checkin e checkout
nome com letra maisúcula status reserva e forma de pagamento

In [301]:
df_fun = pd.read_csv('funcionarios.csv', sep=';')
df_fun

print(df_fun.shape)
display(df_fun.head())
display(df_fun.tail())
display(df_fun.dtypes)

(134, 7)

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar De Limpeza,Governança,2139.0,2020-05-10
1,2,1,Abel Correia,Segurança,Segurança,1746.0,2021-12-29
2,3,1,Sara Teixeira,Analista Financeiro,Financeiro,5356.0,2022-01-03
3,4,1,Julia Monteiro,Auxiliar De Limpeza,Governança,2070.0,2019-10-06
4,5,1,Daniela Ramos,Auxiliar De Limpeza,Governança,1572.0,2018-10-16

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
129,130,12,Fernanda Cruz,Manutenção,Manutenção,2221.0,2020-08-16
130,131,12,Abel Correia,Gerente,Administração,8404.0,2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,2700.0,2021-01-22
132,133,12,Yuri Castro,Segurança,Segurança,1976.0,2021-08-10
133,134,12,Eduardo Lopes,Recepcionista,Recepção,2442.0,2023-02-17

id_funcionario      int64
id_unidade          int64
nome                  str
cargo                 str
departamento          str
salario           float64
data_admissao         str
dtype: object

In [296]:
df_fun['cargo'] = df_fun['cargo'].str.strip().str.title()

In [297]:
df_fun['cargo'].value_counts()

cargo
Manutenção             24
Camareira              21
Segurança              20
Auxiliar De Limpeza    17
Recepcionista          15
Cozinheiro             15
Analista Financeiro    13
Gerente                 9
Name: count, dtype: int64

In [298]:
df_fun['departamento'].value_counts()

departamento
Governança             38
Manutenção             24
Segurança              20
Recepção               15
Alimentos e Bebidas    15
Financeiro             13
Administração           9
Name: count, dtype: int64

In [299]:
dep = {
    'Gov.':                'Governança',
    'Admin.':                  'Administração',
    'A&B':                   'Alimentos e Bebidas',
     'Baixada fluminense':             'Baixada Fluminense'
}
df_fun['departamento'] = df_fun['departamento'].map(dep).fillna(df_fun['departamento'])

print('Após mapeamento:')
print(sorted(df_fun['departamento'].unique()))

Após mapeamento:
['Administração', 'Alimentos e Bebidas', 'Financeiro', 'Governança', 'Manutenção', 'Recepção', 'Segurança']

In [300]:
df_fun['salario'] = (
df_fun['salario']
.str.replace('.', '', regex=False)
.str.replace('"', '', regex=False)
.str.replace(',', '.', regex=False)
.astype(float)
)

AttributeError: Can only use .str accessor with string values, not floating

In [ ]:
df_fun['data_admissao'] = pd.to_datetime(
    df_fun['data_admissao'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [ ]:
display(df_fun.dtypes)
df_fun.to_csv('funcionarios.csv', sep=';', index=False)
df_fun

id_funcionario             int64
id_unidade                 int64
nome                         str
cargo                        str
departamento                 str
salario                  float64
data_admissao     datetime64[us]
dtype: object

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar De Limpeza,Governança,2139.0,2020-05-10
1,2,1,Abel Correia,Segurança,Segurança,1746.0,2021-12-29
2,3,1,Sara Teixeira,Analista Financeiro,Financeiro,5356.0,2022-01-03
3,4,1,Julia Monteiro,Auxiliar De Limpeza,Governança,2070.0,2019-10-06
4,5,1,Daniela Ramos,Auxiliar De Limpeza,Governança,1572.0,2018-10-16
...,...,...,...,...,...,...,...
129,130,12,Fernanda Cruz,Manutenção,Manutenção,2221.0,2020-08-16
130,131,12,Abel Correia,Gerente,Administração,8404.0,2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,2700.0,2021-01-22
132,133,12,Yuri Castro,Segurança,Segurança,1976.0,2021-08-10
133,134,12,Eduardo Lopes,Recepcionista,Recepção,2442.0,2023-02-17

padronizado escrita cargo, com letras maisuculas
padronizado departamento tirado abreviações
sálario padronizado para float e retirado datas
data admissao para datetime

In [302]:
df_cli = pd.read_csv ('clientes.csv', sep=';')
df_cli
print(df_cli.shape)
display(df_cli.head())
display(df_cli.tail())
display(df_cli.dtypes)

(301, 6)

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,Corporativo
1,2,Larissa Sousa,Curitiba,PR,18-25,Pessoa Física
2,3,Tatiana Coelho,Rio de Janeiro,RJ,65+,Corporativo
3,4,Wilson Duarte,Brasília,DF,26-35,Corporativo
4,5,Gabriela Lima,Rio de Janeiro,RJ,46-55,Pessoa Física

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
296,297,Roberta Leite,Curitiba,PR,56-65,Pessoa Física
297,298,Eduardo Lopes,São Paulo,SP,36-45,Corporativo
298,299,Vanessa Cavalcanti,Curitiba,PR,46-55,Pessoa Física
299,300,Julia Monteiro,Brasília,DF,36-45,Corporativo
300,47,Carlos Neto,Niterói,RJ,36-45,Corporativo

id_cliente       int64
nome               str
cidade_origem      str
estado_origem      str
faixa_etaria       str
tipo_cliente       str
dtype: object

In [ ]:
df_cli[df_cli.isnull().any(axis=1)]

In [ ]:
df_cli['cidade_origem'].sort_values().unique()

<StringArray>
['Belo Horizonte',       'Brasília',       'Curitiba',      'Fortaleza',
        'Niterói',         'Recife', 'Rio de Janeiro',       'Salvador',
      'São Paulo']
Length: 9, dtype: str

In [ ]:
df_cli['estado_origem'].sort_values()

In [ ]:
print(sorted(df_cli['cidade_origem'].unique()))
print(sorted(df_cli['estado_origem'].unique()))

['Belo Horizonte', 'Brasília', 'Curitiba', 'Fortaleza', 'Niterói', 'Recife', 'Rio de Janeiro', 'Salvador', 'São Paulo']
['BA', 'CE', 'DF', 'MG', 'PE', 'PR', 'RJ', 'SP']

In [ ]:
mapa_cidades = {
    'r.j.': 'RJ',
    'rj': 'RJ',
    'Rio de Janeiro': 'RJ'
}

df_cli['estado_origem'] = df_cli['estado_origem'].map(mapa_cidades).fillna(df_cli['estado_origem'])

print('Após mapeamento:')
print(sorted(df_cli['estado_origem'].unique()))

Após mapeamento:
['AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MG', 'PA', 'PE', 'PR', 'RJ', 'RS', 'SC', 'SP']

In [ ]:
mapa_cidade_estado = {
    "Belo Horizonte": "MG",
    "Brasília": "DF",
    "Curitiba": "PR",
    "Fortaleza": "CE",
    "Niterói": "RJ",
    "Recife": "PE",
    "Rio de Janeiro": "RJ",
    "Salvador": "BA",
    "São Paulo": "SP"
}


df_cli['estado_origem'] = df_cli['cidade_origem'].map(mapa_cidade_estado).fillna(df_cli['estado_origem'])


df_cli

In [ ]:
df_cli['tipo_cliente'].sort_values().unique()
print(sorted(df_cli['tipo_cliente'].unique()))

['Corporativo', 'Pessoa Física']

In [ ]:
tipo = {
    'PF':   'Pessoa Física',
    'pessoa fisica':    'Pessoa Física',
    'pf':   'Pessoa Física',
    'PJ':   'Corporativo',
    'corporativo':  'Corporativo'
}

df_cli['tipo_cliente'] = df_cli['tipo_cliente'].map(tipo).fillna(df_cli['tipo_cliente'])

print('Após mapeamento:')
print(sorted(df_cli['tipo_cliente'].unique()))

Após mapeamento:
['Corporativo', 'Pessoa Física']

In [ ]:
df_cli
df_cli.to_csv('clientes.csv', sep=';', index=False)

espelhado dados de estado de acordo com a cidade
padronizado escrita do tipo cliente

In [303]:
df_can = pd.read_csv('canais_venda.csv', sep=';')

print(df_tipo.shape)
display(df_tipo.head())
display(df_tipo.tail())
display(df_tipo.dtypes)

(6, 4)

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
0               1      Standard               2              280.0
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0
5               3        Deluxe               3              580.0

id_tipo_quarto         int64
descricao                str
capacidade_max         int64
valor_diaria_base    float64
dtype: object

trabalhar no novos csvs

In [425]:
df_uni = pd.read_csv('unidades_novos.csv', sep=';')

print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

df.info()

(12, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

id_unidade                   int64
nome_unidade                   str
cidade                         str
regiao                         str
categoria_hotel(estrelas)    Int64
num_quartos_total            Int64
dtype: object

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_unidade                 12 non-null     int64
 1   nome_unidade               12 non-null     str
 2   cidade                     12 non-null     str
 3   regiao                     12 non-null     str
 4   categoria_hotel(estrelas)  12 non-null     Int64
 5   num_quartos_total          10 non-null     Int64
dtypes: Int64(2), int64(1), str(3)
memory usage: 732.0 bytes

In [426]:

df = pd.concat([df, df_uni], ignore_index=True)
print (df.shape) 
display (df.head(13))
print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

(13, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

(13, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

id_unidade                   int64
nome_unidade                   str
cidade                         str
regiao                         str
categoria_hotel(estrelas)    Int64
num_quartos_total            Int64
dtype: object

In [427]:
df ['num_quartos_total'] = df ['num_quartos_total'].astype('Int64')
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [428]:
df.info()
df.duplicated().sum()
df[df.duplicated(keep=False)]

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_unidade                 13 non-null     int64
 1   nome_unidade               13 non-null     str
 2   cidade                     13 non-null     str
 3   regiao                     13 non-null     str
 4   categoria_hotel(estrelas)  13 non-null     Int64
 5   num_quartos_total          11 non-null     Int64
dtypes: Int64(2), int64(1), str(3)
memory usage: 782.0 bytes

Empty DataFrame
Columns: [id_unidade, nome_unidade, cidade, regiao, categoria_hotel(estrelas), num_quartos_total]
Index: []

In [429]:
df = df.drop_duplicates()
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [432]:

df.loc[6, "num_quartos_total"] = 70
df.loc[9, "num_quartos_total"] = 75
df.to_csv('unidades.csv', sep=';', index=False)

In [439]:
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,70
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

concatenado csv unidades
preenchido os números de quartos

In [ ]:
df_tipon = pd.read_csv('tipos_quarto_novos.csv', sep=';')
print (df_tipon.shape)
print (df_tipon.dtypes)
df_tipon

In [434]:
df_tipo_qt = pd.concat([df_tipo, df_tipon], ignore_index=True)

In [435]:
df_tipo_qt

   id_tipo_quarto                descricao  capacidade_max  valor_diaria_base
0               1                 Standard               2              280.0
1               2                 Superior               2              420.0
2               3                   Deluxe               3              580.0
3               4                    Suite               4              950.0
4               5             Suíte Master               4             1500.0
5               3                   Deluxe               3              580.0
6               6          Suíte Vista Mar               2              620.0
7               7  Suíte Master Copacabana               3              780.0
8               8   Cobertura Presidencial               4              950.0

In [436]:
df_tipo_qt = df_tipo_qt.drop_duplicates()
df_tipo_qt

   id_tipo_quarto                descricao  capacidade_max  valor_diaria_base
0               1                 Standard               2              280.0
1               2                 Superior               2              420.0
2               3                   Deluxe               3              580.0
3               4                    Suite               4              950.0
4               5             Suíte Master               4             1500.0
6               6          Suíte Vista Mar               2              620.0
7               7  Suíte Master Copacabana               3              780.0
8               8   Cobertura Presidencial               4              950.0

In [437]:
df_tipo_qt.to_csv('tipos_quarto.csv', sep=';', index=False)

concatenado tipo quarto

In [ ]:
df_res = pd.read_csv ('reservas.csv', sep=';')
df_reser = pd.read_csv('reservas_novas.csv', sep=';')
df_reser.info()
df_res.info()

In [ ]:
df_reserva = pd.concat([df_res, df_reser], ignore_index=True)
df_reserva

In [387]:

df_reserva

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,Confirmada,Cartão De Crédito
1,2,5,1,261,4.0,2023-09-28,2023-10-01,3,2,1.0,Concluída,Pix
2,3,10,4,49,4.0,2023-08-01,2023-08-06,5,1,9.0,Concluída,Cartão De Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,Cancelada,Pix
4,5,7,1,42,1.0,2023-01-12,2023-01-19,7,1,6.0,Confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
4659,3198,7,5,268,1.0,2026-05-08,2026-07-08,2,2,9.0,Confirmada,Cartão De Débito
4660,3490,9,3,48,1.0,2026-05-24,2026-05-26,2,3,8.0,Confirmada,Transferência
4661,4579,13,6,306,4.0,2026-04-16,2026-04-18,2,4,NaN,Confirmada,Dinheiro
4662,3882,11,1,100,4.0,2025-03-01,2025-06-01,3,1,8.0,Confirmada,Cartão De Débito
4663,4183,3,1,102,1.0,2025-07-11,2025-09-11,2,1,3.0,Confirmada,Pix

In [ ]:
df_reserva.loc[727, 'qtd_diarias'] = 7
df_reserva.loc[954, 'qtd_diarias'] = 4
df_reserva.loc[1133, 'qtd_diarias'] = 3
df_reserva.loc[1151, 'qtd_diarias'] = 2
df_reserva.loc[1447, 'qtd_diarias'] = 6
df_reserva.loc[1580, 'qtd_diarias'] = 4
df_reserva.loc[2311, 'qtd_diarias'] = 4
df_reserva.loc[2383, 'qtd_diarias'] = 2
df_reserva.loc[2383, 'qtd_diarias'] = 2
df_reserva.loc[2383, 'qtd_diarias'] = 2
df_reserva.loc[2383, 'qtd_diarias'] = 2
df_reserva.loc[2383, 'qtd_diarias'] = 2

In [464]:
df_reserva.iloc[727, :]
df_reserva.iloc[954, :]
df_reserva.iloc[1133, :]
df_reserva.iloc[1151, :]
df_reserva.iloc[1447, :]
df_reserva.iloc[1580, :]
df_reserva.iloc[2311, :]
df_reserva.iloc[2383, :]
df_reserva.iloc[3471, :]

id_reserva                          2848
id_unidade                             4
id_tipo_quarto                         3
id_cliente                           173
id_canal                             4.0
data_checkin         2025-08-23 00:00:00
data_checkout        2025-08-25 00:00:00
qtd_diarias                            2
num_hospedes                           2
avaliacao_hospede                    7.0
status_reserva                Confirmada
forma_pagamento            Transferência
Name: 3471, dtype: object

In [ ]:
df_reserva['data_checkout'] = pd.to_datetime(
    df_reserva['data_checkout'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)
df_reserva['data_checkin'] = pd.to_datetime(
    df_reserva['data_checkin'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

df_reserva['status_reserva'] = df_reserva['status_reserva'].str.strip().str.title()
df_reserva['forma_pagamento'] = df_reserva['forma_pagamento'].str.strip().str.title()
df_reserva.info()

In [383]:
print (df_reserva['status_reserva'].sort_values().unique())
print(df_reserva['forma_pagamento'].sort_values().unique())

<StringArray>
[   'Cancel.',  'Cancelada',  'Concluida',  'Concluída',      'Conf.',
 'Confirmada',    'No-Show']
Length: 7, dtype: str
<StringArray>
[       'C. Crédito',    'Cartao Credito',     'Cartao Debito',
 'Cartão De Crédito',  'Cartão De Débito',              'Cash',
                'Cc',                'Cd',              'Cred',
          'Dinheiro',               'Déb',               'Pix',
               'Ted',     'Transferencia',     'Transferência']
Length: 15, dtype: str

In [ ]:
rese = {
    'Cancel.':                'Cancelada',
    'Concluida':                  'Concluída',
    'Conf.':                   'Confirmada'
    }
df_reserva['status_reserva'] = df_reserva['status_reserva'].map(rese).fillna(df_reserva['status_reserva'])

print('Após mapeamento:')
print(sorted(df_reserva['status_reserva'].unique()))

df_reserva

In [ ]:
forma = {
    'C. Crédito':                'Cartão De Crédito',
    'Cartao Credito':            'Cartão De Crédito',
    'Cred':                      'Cartão De Crédito',
    'Cc':                        'Cartão De Crédito',
    'Cartao Debito':             'Cartão De Débito',
    'Cd':                        'Cartão De Débito',
    'Déb':                       'Cartão De Débito',
    'Cash':                      'Dinheiro',
    'Ted':                       'Transferência',
    'Transferencia':             'Transferência'

    }
df_reserva['forma_pagamento'] = df_reserva['forma_pagamento'].map(forma).fillna(df_reserva['forma_pagamento'])

print('Após mapeamento:')
print(sorted(df_reserva['forma_pagamento'].unique()))

df_reserva

df_reserva.duplicated().sum()
df_reserva[df_reserva.duplicated(keep=False)]
df_reserva.duplicated(subset=['id_reserva',	'id_unidade',	'id_tipo_quarto',	'id_cliente',	'id_canal',	'data_checkin',	'data_checkout',	'qtd_diarias', 'num_hospedes',	'avaliacao_hospede',	'status_reserva',	'forma_pagamento' ]).sum()

In [386]:
df_reserva.duplicated().sum()

np.int64(15)

df_reserva = df_reserva.drop_duplicates()
df_reserva.duplicated().sum()