In [5]:
import pandas as pd 
import numpy as np

In [6]:
pd.read_csv ('canais_venda.csv', sep=';')
pd.read_csv ('funcionarios_novos.csv', sep=';')
pd.read_csv ('reservas_novas.csv', sep=';')
pd.read_csv ('tipos_quarto_novos.csv', sep=';')
pd.read_csv ('unidades_novos.csv', sep=';')

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [3]:
df = pd.read_csv('unidades_novos.csv', sep=';')

print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

(1, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5 estrelas,40.0

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5 estrelas,40.0

id_unidade             int64
nome_unidade             str
cidade                   str
regiao                   str
categoria_hotel          str
num_quartos_total    float64
dtype: object

In [4]:
df['categoria_hotel'].value_counts()

categoria_hotel
5 estrelas    1
Name: count, dtype: int64

In [5]:
df[df.duplicated(subset=['num_quartos_total'], keep=False)]

Empty DataFrame
Columns: [id_unidade, nome_unidade, cidade, regiao, categoria_hotel, num_quartos_total]
Index: []

In [6]:
mapa = {
    '5 estrelas':                '5',
    'cinco estrelas':            '5'
}
df['categoria_hotel'] = df['categoria_hotel'].map(mapa).fillna(df['categoria_hotel'])

print('Após mapeamento:')
print(sorted(df['categoria_hotel'].unique()))

Após mapeamento:
['5']

In [7]:
df['categoria_hotel'].value_counts()

categoria_hotel
5    1
Name: count, dtype: int64

In [8]:
df['regiao'].value_counts()

regiao
Capital    1
Name: count, dtype: int64

In [9]:
df['regiao'] = df['regiao'].str.strip().str.title()
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40.0

In [10]:
df['num_quartos_total'] = df['num_quartos_total'].astype("Int64")
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [11]:
df = df.rename(columns={'categoria_hotel': 'categoria_hotel(estrelas)'})
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [12]:
df['categoria_hotel(estrelas)'] = pd.to_numeric(df['categoria_hotel(estrelas)'], errors="coerce").astype("Int64")
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [18]:
df.to_csv('unidades_novos.csv', sep=';', index=False)
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5,40

In [14]:
df_tipo = pd.read_csv('tipos_quarto_novos.csv', sep=';')

print(df_tipo.shape)
display(df_tipo.head())
display(df_tipo.tail())
display(df_tipo.dtypes)

(3, 4)

   id_tipo_quarto                descricao  capacidade_max valor_diaria_base
0               6          Suíte Vista Mar               2         R$ 620,00
1               7  Suíte Master Copacabana               3         R$ 780,00
2               8   Cobertura Presidencial               4         R$ 950,00

   id_tipo_quarto                descricao  capacidade_max valor_diaria_base
0               6          Suíte Vista Mar               2         R$ 620,00
1               7  Suíte Master Copacabana               3         R$ 780,00
2               8   Cobertura Presidencial               4         R$ 950,00

id_tipo_quarto       int64
descricao              str
capacidade_max       int64
valor_diaria_base      str
dtype: object

In [15]:
df_tipo['valor_diaria_base'] = (
df_tipo['valor_diaria_base']
.str.replace('R$', '', regex=False)
.str.replace(' ', '', regex=False)
.str.replace('.', '', regex=False) # remove separador de milhar
.str.replace(',', '.', regex=False)
.astype(float)
)

In [19]:
df_tipo.to_csv('tipos_quarto_novos.csv', sep=';', index=False)

In [20]:
df_tipo

   id_tipo_quarto                descricao  capacidade_max  valor_diaria_base
0               6          Suíte Vista Mar               2              620.0
1               7  Suíte Master Copacabana               3              780.0
2               8   Cobertura Presidencial               4              950.0

In [21]:
df_tipo = pd.read_csv('reservas_novas.csv', sep=';')

print(df_tipo.shape)
display(df_tipo.head())
display(df_tipo.tail())
display(df_tipo.dtypes)

(2207, 12)

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,3787,11,2,42,4.0,2025-09-23,2025-09-25,2,2,8.0,concluída,Cartão de Crédito
1,3638,10,2,17,4.0,2025-03-12,2025-03-13,1,3,NaN,confirmada,PIX
2,2950,4,3,275,2.0,2025-06-25,2025-07-01,6,3,10.0,concluída,Dinheiro
3,2582,1,4,81,1.0,2025-10-02,2025-10-03,1,2,8.0,cancelada,Transferência
4,3084,6,2,4,1.0,2026-01-14,2026-01-19,5,2,8.0,confirmada,Transferência

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
2202,3198,7,5,268,1.0,2026-08-05,2026-08-07,2,2,9.0,confirmada,Cartão de Débito
2203,3490,9,3,48,1.0,2026-05-24,2026-05-26,2,3,8.0,CONFIRMADA,Transferência
2204,4579,13,6,306,4.0,2026-04-16,2026-04-18,2,4,NaN,confirmada,Dinheiro
2205,3882,11,1,100,4.0,2025-01-03,2025-01-06,3,1,8.0,CONFIRMADA,CD
2206,4183,3,1,102,1.0,2025-11-07,2025-11-09,2,1,3.0,confirmada,PIX

id_reserva             int64
id_unidade             int64
id_tipo_quarto         int64
id_cliente             int64
id_canal             float64
data_checkin             str
data_checkout            str
qtd_diarias            int64
num_hospedes           int64
avaliacao_hospede    float64
status_reserva           str
forma_pagamento          str
dtype: object

In [22]:
df_tipo['status_reserva'] = df_tipo['status_reserva'].str.strip().str.title()
df_tipo

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,3787,11,2,42,4.0,2025-09-23,2025-09-25,2,2,8.0,Concluída,Cartão de Crédito
1,3638,10,2,17,4.0,2025-03-12,2025-03-13,1,3,NaN,Confirmada,PIX
2,2950,4,3,275,2.0,2025-06-25,2025-07-01,6,3,10.0,Concluída,Dinheiro
3,2582,1,4,81,1.0,2025-10-02,2025-10-03,1,2,8.0,Cancelada,Transferência
4,3084,6,2,4,1.0,2026-01-14,2026-01-19,5,2,8.0,Confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
2202,3198,7,5,268,1.0,2026-08-05,2026-08-07,2,2,9.0,Confirmada,Cartão de Débito
2203,3490,9,3,48,1.0,2026-05-24,2026-05-26,2,3,8.0,Confirmada,Transferência
2204,4579,13,6,306,4.0,2026-04-16,2026-04-18,2,4,NaN,Confirmada,Dinheiro
2205,3882,11,1,100,4.0,2025-01-03,2025-01-06,3,1,8.0,Confirmada,CD
2206,4183,3,1,102,1.0,2025-11-07,2025-11-09,2,1,3.0,Confirmada,PIX

In [7]:
df_tipo = pd.read_csv('canais_venda.csv', sep=';')

print(df_tipo.shape)
display(df_tipo.head())
display(df_tipo.tail())
display(df_tipo.dtypes)

(4, 3)

   id_canal    nome_canal comissao_pct
0         1  Site Próprio           8%
1         2           ota          18%
2         3      Telefone           5%
3         4       agencia          12%

   id_canal    nome_canal comissao_pct
0         1  Site Próprio           8%
1         2           ota          18%
2         3      Telefone           5%
3         4       agencia          12%

id_canal        int64
nome_canal        str
comissao_pct      str
dtype: object

In [8]:
df_tipo['nome_canal'].value_counts()

nome_canal
Site Próprio    1
ota             1
Telefone        1
agencia         1
Name: count, dtype: int64

In [9]:
df_tipo['nome_canal'] = df_tipo['nome_canal'].str.strip().str.title()
df_tipo

   id_canal    nome_canal comissao_pct
0         1  Site Próprio           8%
1         2           Ota          18%
2         3      Telefone           5%
3         4       Agencia          12%

In [10]:
df_tipo['comissao_pct'].value_counts()

comissao_pct
8%     1
18%    1
5%     1
12%    1
Name: count, dtype: int64

In [13]:
df_tipo["comissao_pct"] = (
    df_tipo["comissao_pct"]
    .str.replace("%", "", regex=False)
    .str.replace(",", ".", regex=False)
    .astype(float)
)

In [14]:
df_tipo

   id_canal    nome_canal  comissao_pct
0         1  Site Próprio           8.0
1         2           Ota          18.0
2         3      Telefone           5.0
3         4       Agencia          12.0

In [15]:
df_tipo.to_csv('canais_venda.csv', sep=';', index=False)

In [16]:
df_tipo

   id_canal    nome_canal  comissao_pct
0         1  Site Próprio           8.0
1         2           Ota          18.0
2         3      Telefone           5.0
3         4       Agencia          12.0