In [32]:
import pandas as pd 
import numpy as np

In [33]:
pd.read_csv ('reservas_novas.csv', sep=';')

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50.0

In [34]:
df = pd.read_csv('reservas_novas.csv', sep=';')

print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

(12, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50.0

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50.0

id_unidade                     int64
nome_unidade                     str
cidade                           str
regiao                           str
categoria_hotel(estrelas)      int64
num_quartos_total            float64
dtype: object

In [35]:
df['cidade'].value_counts()

cidade
Rio de Janeiro    4
Nova Iguaçu       2
Petrópolis        1
Teresópolis       1
Nova Friburgo     1
Paraty            1
Angra dos Reis    1
Mangaratiba       1
Name: count, dtype: int64

In [36]:
df['regiao'].value_counts()

regiao
Capital               4
Serra                 3
Costa Verde           3
Baixada Fluminense    2
Name: count, dtype: int64

In [37]:
df['nome_unidade'].value_counts()

nome_unidade
NaraHoteis Ipanema               1
NaraHoteis Barra da Tijuca       1
NaraHoteis Centro                1
NaraHoteis Santa Teresa          1
NaraHoteis Nova Iguaçu Centro    1
NaraHoteis Nova Iguaçu Park      1
NaraHoteis Petrópolis            1
NaraHoteis Teresópolis           1
NaraHoteis Friburgo              1
NaraHoteis Paraty                1
NaraHoteis Angra dos Reis        1
NaraHoteis Mangaratiba           1
Name: count, dtype: int64

In [47]:
df['num_quartos_total'] = df['num_quartos_total'].astype('Int64')
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,<NA>
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,<NA>
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4,50

In [81]:
df.to_csv('reservas_novas.csv', sep=';', index=False)
df

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,135,13,Marcos Andrade,Concierge,Governança,3987710.0,2024-05-22
1,136,13,Fernanda Lopes,Sommelier,Governança,2432010.0,2024-05-04
2,137,13,Ricardo Nunes,Sommelier,A&B,3651510.0,2025-12-07
3,138,13,Patrícia Melo,analista financeiro,A&B,8545890.0,2024-12-06
4,139,13,Bruno Cardoso,Auxiliar de Limpeza,Financeiro,9187660.0,2024-10-12
5,140,13,Camila Ferreira,Segurança,Governança,4710880.0,2024-09-27
6,141,13,Diego Ramos,analista financeiro,A&B,8932760.0,2024-03-21
7,142,13,Juliana Prado,Chef de Cozinha,Operações,NaN,2024-12-03
8,143,13,Leonardo Vaz,Manobrista,operações,2782480.0,2024-08-26
9,144,13,Renata Castro,Segurança,Financeiro,8289010.0,2024-06-15

In [44]:
df[df['num_quartos_total'].isna()]

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel(estrelas),num_quartos_total
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5,NaN
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5,NaN

In [45]:
df[df['num_quartos_total'].isin([float('inf'), float('-inf')])]

Empty DataFrame
Columns: [id_unidade, nome_unidade, cidade, regiao, categoria_hotel(estrelas), num_quartos_total]
Index: []

In [ ]:
pd.read_csv ('reservas_novas.csv', sep=';')

In [48]:
df = pd.read_csv('funcionarios_novos.csv', sep=';')

print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

(10, 7)

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,135,13,Marcos Andrade,Concierge,Governança,"""3.987,71""",2024-05-22
1,136,13,Fernanda Lopes,Sommelier,Governança,"""2.432,01""",2024-04-05
2,137,13,Ricardo Nunes,Sommelier,A&B,"""3.651,51""",2025-07-12
3,138,13,Patrícia Melo,analista financeiro,A&B,"""8.545,89""",2024-06-12
4,139,13,Bruno Cardoso,Auxiliar de Limpeza,Financeiro,"""9.187,66""",2024-12-10

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
5,140,13,Camila Ferreira,Segurança,Governança,"""4.710,88""",2024-09-27
6,141,13,Diego Ramos,analista financeiro,A&B,"""8.932,76""",2024-03-21
7,142,13,Juliana Prado,Chef de Cozinha,Operações,NaN,2024-03-12
8,143,13,Leonardo Vaz,Manobrista,operações,"""2.782,48""",2024-08-26
9,144,13,Renata Castro,Segurança,Financeiro,"""8.289,01""",2024-06-15

id_funcionario    int64
id_unidade        int64
nome                str
cargo               str
departamento        str
salario             str
data_admissao       str
dtype: object

In [73]:
df['salario'] = (
    df['salario']
    .astype(str)
    .str.replace('"', '', regex=False)
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)
df

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,135,13,Marcos Andrade,Concierge,Governança,3987710.0,2024-05-22
1,136,13,Fernanda Lopes,Sommelier,Governança,2432010.0,2024-04-05
2,137,13,Ricardo Nunes,Sommelier,A&B,3651510.0,2025-07-12
3,138,13,Patrícia Melo,analista financeiro,A&B,8545890.0,2024-06-12
4,139,13,Bruno Cardoso,Auxiliar de Limpeza,Financeiro,9187660.0,2024-12-10
5,140,13,Camila Ferreira,Segurança,Governança,4710880.0,2024-09-27
6,141,13,Diego Ramos,analista financeiro,A&B,8932760.0,2024-03-21
7,142,13,Juliana Prado,Chef de Cozinha,Operações,NaN,2024-03-12
8,143,13,Leonardo Vaz,Manobrista,operações,2782480.0,2024-08-26
9,144,13,Renata Castro,Segurança,Financeiro,8289010.0,2024-06-15

In [77]:
df['data_admissao'] = pd.to_datetime(
    df['data_admissao'],
    format='mixed',
    dayfirst=True
)
df

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,135,13,Marcos Andrade,Concierge,Governança,3987710.0,2024-05-22
1,136,13,Fernanda Lopes,Sommelier,Governança,2432010.0,2024-05-04
2,137,13,Ricardo Nunes,Sommelier,A&B,3651510.0,2025-12-07
3,138,13,Patrícia Melo,analista financeiro,A&B,8545890.0,2024-12-06
4,139,13,Bruno Cardoso,Auxiliar de Limpeza,Financeiro,9187660.0,2024-10-12
5,140,13,Camila Ferreira,Segurança,Governança,4710880.0,2024-09-27
6,141,13,Diego Ramos,analista financeiro,A&B,8932760.0,2024-03-21
7,142,13,Juliana Prado,Chef de Cozinha,Operações,NaN,2024-12-03
8,143,13,Leonardo Vaz,Manobrista,operações,2782480.0,2024-08-26
9,144,13,Renata Castro,Segurança,Financeiro,8289010.0,2024-06-15

In [80]:
df.to_csv('funcionarios_novos.csv', sep=';', index=False)
df

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,135,13,Marcos Andrade,Concierge,Governança,3987710.0,2024-05-22
1,136,13,Fernanda Lopes,Sommelier,Governança,2432010.0,2024-05-04
2,137,13,Ricardo Nunes,Sommelier,A&B,3651510.0,2025-12-07
3,138,13,Patrícia Melo,analista financeiro,A&B,8545890.0,2024-12-06
4,139,13,Bruno Cardoso,Auxiliar de Limpeza,Financeiro,9187660.0,2024-10-12
5,140,13,Camila Ferreira,Segurança,Governança,4710880.0,2024-09-27
6,141,13,Diego Ramos,analista financeiro,A&B,8932760.0,2024-03-21
7,142,13,Juliana Prado,Chef de Cozinha,Operações,NaN,2024-12-03
8,143,13,Leonardo Vaz,Manobrista,operações,2782480.0,2024-08-26
9,144,13,Renata Castro,Segurança,Financeiro,8289010.0,2024-06-15

In [78]:
df['data_admissao'].dtype

dtype('<M8[us]')

In [79]:
df['data_admissao'].head()

0   2024-05-22
1   2024-05-04
2   2025-12-07
3   2024-12-06
4   2024-10-12
Name: data_admissao, dtype: datetime64[us]

In [56]:
df[df['salario'].isna()]

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
7,142,13,Juliana Prado,Chef de Cozinha,Operações,NaN,2024-03-12

In [65]:
df[df[''].isna()]

Empty DataFrame
Columns: [id_funcionario, id_unidade, nome, cargo, departamento, salario, data_admissao]
Index: []

In [49]:
df['nome'].value_counts()

nome
Marcos Andrade     1
Fernanda Lopes     1
Ricardo Nunes      1
Patrícia Melo      1
Bruno Cardoso      1
Camila Ferreira    1
Diego Ramos        1
Juliana Prado      1
Leonardo Vaz       1
Renata Castro      1
Name: count, dtype: int64

In [50]:
df['cargo'].value_counts()

cargo
Sommelier              2
analista financeiro    2
Segurança              2
Concierge              1
Auxiliar de Limpeza    1
Chef de Cozinha        1
Manobrista             1
Name: count, dtype: int64

In [51]:
df['departamento'].value_counts()

departamento
Governança    3
A&B           3
Financeiro    2
Operações     1
operações     1
Name: count, dtype: int64

In [52]:
df[''].value_counts()

id_funcionario
135    1
136    1
137    1
138    1
139    1
140    1
141    1
142    1
143    1
144    1
Name: count, dtype: int64